//
// Generated by Bluespec Compiler (build 399b09c5)
//
// On Sun Mar 13 11:04:35 CET 2022
//
//
// Ports:
// Name                         I/O  size props
// RDY_request_put                O     1
// response_get                   O    69 reg
// RDY_response_get               O     1 reg
// CLK                            I     1 clock
// RST_N                          I     1 reset
// request_put                    I   196 reg
// EN_request_put                 I     1
// EN_response_get                I     1
//
// Combinational paths from inputs to outputs:
//   EN_response_get -> RDY_request_put
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkDoubleFMA(CLK,
		   RST_N,

		   request_put,
		   EN_request_put,
		   RDY_request_put,

		   EN_response_get,
		   response_get,
		   RDY_response_get);
  input  CLK;
  input  RST_N;

  // action method request_put
  input  [195 : 0] request_put;
  input  EN_request_put;
  output RDY_request_put;

  // actionvalue method response_get
  input  EN_response_get;
  output [68 : 0] response_get;
  output RDY_response_get;

  // signals for module outputs
  wire [68 : 0] response_get;
  wire RDY_request_put, RDY_response_get;

  // ports of submodule fpu_fOperand_S0
  wire [195 : 0] fpu_fOperand_S0$D_IN, fpu_fOperand_S0$D_OUT;
  wire fpu_fOperand_S0$CLR,
       fpu_fOperand_S0$DEQ,
       fpu_fOperand_S0$EMPTY_N,
       fpu_fOperand_S0$ENQ,
       fpu_fOperand_S0$FULL_N;

  // ports of submodule fpu_fProd_S2
  wire [105 : 0] fpu_fProd_S2$D_IN, fpu_fProd_S2$D_OUT;
  wire fpu_fProd_S2$CLR,
       fpu_fProd_S2$DEQ,
       fpu_fProd_S2$EMPTY_N,
       fpu_fProd_S2$ENQ,
       fpu_fProd_S2$FULL_N;

  // ports of submodule fpu_fProd_S3
  wire [105 : 0] fpu_fProd_S3$D_IN, fpu_fProd_S3$D_OUT;
  wire fpu_fProd_S3$CLR,
       fpu_fProd_S3$DEQ,
       fpu_fProd_S3$EMPTY_N,
       fpu_fProd_S3$ENQ,
       fpu_fProd_S3$FULL_N;

  // ports of submodule fpu_fResult_S9
  wire [68 : 0] fpu_fResult_S9$D_IN, fpu_fResult_S9$D_OUT;
  wire fpu_fResult_S9$CLR,
       fpu_fResult_S9$DEQ,
       fpu_fResult_S9$EMPTY_N,
       fpu_fResult_S9$ENQ,
       fpu_fResult_S9$FULL_N;

  // ports of submodule fpu_fState_S1
  wire [257 : 0] fpu_fState_S1$D_IN, fpu_fState_S1$D_OUT;
  wire fpu_fState_S1$CLR,
       fpu_fState_S1$DEQ,
       fpu_fState_S1$EMPTY_N,
       fpu_fState_S1$ENQ,
       fpu_fState_S1$FULL_N;

  // ports of submodule fpu_fState_S2
  wire [151 : 0] fpu_fState_S2$D_IN, fpu_fState_S2$D_OUT;
  wire fpu_fState_S2$CLR,
       fpu_fState_S2$DEQ,
       fpu_fState_S2$EMPTY_N,
       fpu_fState_S2$ENQ,
       fpu_fState_S2$FULL_N;

  // ports of submodule fpu_fState_S3
  wire [151 : 0] fpu_fState_S3$D_IN, fpu_fState_S3$D_OUT;
  wire fpu_fState_S3$CLR,
       fpu_fState_S3$DEQ,
       fpu_fState_S3$EMPTY_N,
       fpu_fState_S3$ENQ,
       fpu_fState_S3$FULL_N;

  // ports of submodule fpu_fState_S4
  wire [203 : 0] fpu_fState_S4$D_IN, fpu_fState_S4$D_OUT;
  wire fpu_fState_S4$CLR,
       fpu_fState_S4$DEQ,
       fpu_fState_S4$EMPTY_N,
       fpu_fState_S4$ENQ,
       fpu_fState_S4$FULL_N;

  // ports of submodule fpu_fState_S5
  wire [215 : 0] fpu_fState_S5$D_IN, fpu_fState_S5$D_OUT;
  wire fpu_fState_S5$CLR,
       fpu_fState_S5$DEQ,
       fpu_fState_S5$EMPTY_N,
       fpu_fState_S5$ENQ,
       fpu_fState_S5$FULL_N;

  // ports of submodule fpu_fState_S6
  wire [202 : 0] fpu_fState_S6$D_IN, fpu_fState_S6$D_OUT;
  wire fpu_fState_S6$CLR,
       fpu_fState_S6$DEQ,
       fpu_fState_S6$EMPTY_N,
       fpu_fState_S6$ENQ,
       fpu_fState_S6$FULL_N;

  // ports of submodule fpu_fState_S7
  wire [202 : 0] fpu_fState_S7$D_IN, fpu_fState_S7$D_OUT;
  wire fpu_fState_S7$CLR,
       fpu_fState_S7$DEQ,
       fpu_fState_S7$EMPTY_N,
       fpu_fState_S7$ENQ,
       fpu_fState_S7$FULL_N;

  // ports of submodule fpu_fState_S8
  wire [140 : 0] fpu_fState_S8$D_IN, fpu_fState_S8$D_OUT;
  wire fpu_fState_S8$CLR,
       fpu_fState_S8$DEQ,
       fpu_fState_S8$EMPTY_N,
       fpu_fState_S8$ENQ,
       fpu_fState_S8$FULL_N;

  // rule scheduling signals
  wire CAN_FIRE_RL_fpu_s1_stage,
       CAN_FIRE_RL_fpu_s2_stage,
       CAN_FIRE_RL_fpu_s3_stage,
       CAN_FIRE_RL_fpu_s4_stage,
       CAN_FIRE_RL_fpu_s5_stage,
       CAN_FIRE_RL_fpu_s6_stage,
       CAN_FIRE_RL_fpu_s7_stage,
       CAN_FIRE_RL_fpu_s8_stage,
       CAN_FIRE_RL_fpu_s9_stage,
       CAN_FIRE_request_put,
       CAN_FIRE_response_get,
       WILL_FIRE_RL_fpu_s1_stage,
       WILL_FIRE_RL_fpu_s2_stage,
       WILL_FIRE_RL_fpu_s3_stage,
       WILL_FIRE_RL_fpu_s4_stage,
       WILL_FIRE_RL_fpu_s5_stage,
       WILL_FIRE_RL_fpu_s6_stage,
       WILL_FIRE_RL_fpu_s7_stage,
       WILL_FIRE_RL_fpu_s8_stage,
       WILL_FIRE_RL_fpu_s9_stage,
       WILL_FIRE_request_put,
       WILL_FIRE_response_get;

  // remaining internal signals
  reg [62 : 0] CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q17,
	       CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q18,
	       CASE_fpu_fState_S8D_OUT_BITS_70_TO_68_0_CASE__ETC__q19;
  reg [51 : 0] CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q1,
	       CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q2,
	       _theResult___fst_sfd__h46445;
  reg [10 : 0] CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q11,
	       CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q12,
	       _theResult___fst_exp__h46444;
  reg CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q13,
      CASE_fpu_fState_S8D_OUT_BITS_70_TO_68_0_CASE__ETC__q14;
  wire [139 : 0] IF_NOT_fpu_fState_S4_first__51_BIT_130_57_62_O_ETC___d799;
  wire [118 : 0] IF_fpu_fOperand_S0_first_BITS_129_TO_119_9_EQ__ETC___d163;
  wire [105 : 0] IF_0_CONCAT_IF_IF_7170_MINUS_fpu_fState_S3_fir_ETC__q4,
		 _theResult___fst__h20644,
		 _theResult___snd__h34784,
		 _theResult___snd__h34798,
		 _theResult___snd__h34800,
		 _theResult___snd__h34812,
		 _theResult___snd__h34818,
		 _theResult___snd__h34836,
		 _theResult___snd__h34841,
		 fpu_fProd_S3_first__13_SRL_IF_7170_MINUS_fpu_f_ETC___d216,
		 sfdBC__h19463,
		 sfdin__h34761,
		 x__h20713;
  wire [68 : 0] IF_fpu_fState_S8_first__164_BIT_67_167_AND_IF__ETC___d1285;
  wire [63 : 0] IF_IF_fpu_fOperand_S0_first_BIT_195_THEN_IF_fp_ETC___d140,
		IF_IF_fpu_fOperand_S0_first_BIT_195_THEN_IF_fp_ETC___d143,
		IF_fpu_fOperand_S0_first_BITS_129_TO_119_9_EQ__ETC___d142;
  wire [62 : 0] IF_0b0_CONCAT_NOT_fpu_fState_S8_first__164_BIT_ETC___d1269,
		IF_IF_7170_MINUS_fpu_fState_S3_first__99_BITS__ETC___d738,
		IF_IF_fpu_fOperand_S0_first_BIT_195_THEN_IF_fp_ETC___d135,
		IF_IF_fpu_fState_S7_first__55_BIT_128_61_THEN__ETC___d1156,
		IF_fpu_fOperand_S0_first_BITS_129_TO_119_9_EQ__ETC___d136,
		IF_fpu_fOperand_S0_first_BIT_195_THEN_fpu_fOpe_ETC___d115,
		IF_fpu_fState_S3_first__99_BITS_12_TO_0_05_SLE_ETC___d740;
  wire [56 : 0] IF_0_CONCAT_IF_IF_fpu_fState_S7_first__55_BIT__ETC__q9,
		_theResult___snd__h45223,
		_theResult___snd__h45237,
		_theResult___snd__h45239,
		_theResult___snd__h45251,
		_theResult___snd__h45257,
		_theResult___snd__h45275,
		_theResult___snd__h45280,
		fpu_fState_S5_first__05_BITS_56_TO_0_14_SRL_IF_ETC___d819,
		guard__h36191,
		result__h36196,
		sfdA__h35382,
		sfdBC__h35383,
		sfd__h36933,
		sfdin__h45200,
		x__h35761,
		x__h35765,
		x__h36183,
		x__h36698,
		x__h36707;
  wire [53 : 0] sfd__h45862;
  wire [52 : 0] x__h18075, x__h18087;
  wire [51 : 0] _theResult___fst_sfd__h394,
		_theResult___sfd__h46367,
		out_sfd__h46370,
		sfd__h3217,
		sfd__h3220,
		sfd__h3223;
  wire [12 : 0] IF_fpu_fState_S4_first__51_BITS_128_TO_118_68__ETC___d772,
		IF_fpu_fState_S4_first__51_BITS_64_TO_54_63_EQ_ETC___d767,
		_7170_MINUS_fpu_fState_S3_first__99_BITS_12_TO__ETC___d211,
		value__h34701,
		value__h45138,
		x__h20746,
		x__h36295;
  wire [11 : 0] IF_IF_7170_MINUS_fpu_fState_S3_first__99_BITS__ETC___d235,
		IF_IF_7170_MINUS_fpu_fState_S3_first__99_BITS__ETC___d666,
		IF_fpu_fState_S7_first__55_BITS_126_TO_114_66__ETC___d1107,
		IF_fpu_fState_S7_first__55_BITS_126_TO_114_66__ETC___d872;
  wire [10 : 0] IF_fpu_fState_S8_first__164_BITS_65_TO_55_168__ETC___d1190,
		IF_fpu_fState_S8_first__164_BITS_65_TO_55_168__ETC___d1215,
		_theResult___exp__h46366,
		_theResult___fst_exp__h34767,
		_theResult___fst_exp__h34770,
		_theResult___fst_exp__h34789,
		_theResult___fst_exp__h34804,
		_theResult___fst_exp__h34843,
		_theResult___fst_exp__h34849,
		_theResult___fst_exp__h34852,
		_theResult___fst_exp__h45206,
		_theResult___fst_exp__h45209,
		_theResult___fst_exp__h45228,
		_theResult___fst_exp__h45243,
		_theResult___fst_exp__h45282,
		_theResult___fst_exp__h45288,
		_theResult___fst_exp__h45291,
		din_exp4684_MINUS_1023__q3,
		din_exp__h34684,
		din_inc___2_exp__h46451,
		fpu_fOperand_S0D_OUT_BITS_129_TO_119_MINUS_1023__q15,
		fpu_fOperand_S0D_OUT_BITS_65_TO_55_MINUS_1023__q16,
		fpu_fState_S4D_OUT_BITS_128_TO_118_MINUS_1023__q7,
		fpu_fState_S4D_OUT_BITS_64_TO_54_MINUS_1023__q6,
		out_exp__h46369,
		value5138_BITS_10_TO_0_MINUS_1023__q8,
		x__h321;
  wire [6 : 0] IF_IF_7170_MINUS_fpu_fState_S3_first__99_BITS__ETC___d664;
  wire [5 : 0] IF_IF_fpu_fState_S7_first__55_BIT_128_61_THEN__ETC___d1105;
  wire [4 : 0] IF_fpu_fState_S3_first__99_BIT_151_00_THEN_fpu_ETC___d729,
	       fpu_fState_S3_first__99_BITS_86_TO_82_04_OR_0__ETC___d705,
	       fpu_fState_S7_first__55_BITS_137_TO_133_60_OR__ETC___d1146,
	       fpu_fState_S8_first__164_BITS_75_TO_71_239_OR__ETC___d1247;
  wire [2 : 0] NOT_fpu_fState_S3_first__99_BITS_12_TO_0_05_SL_ETC___d727;
  wire [1 : 0] IF_sfdin4761_BIT_53_THEN_2_ELSE_0__q5,
	       IF_sfdin5200_BIT_4_THEN_2_ELSE_0__q10,
	       _theResult___snd_fst__h34869,
	       _theResult___snd_fst__h45308,
	       _theResult___snd_snd__h35189,
	       _theResult___snd_snd_snd__h35187,
	       guardBC__h19467,
	       guard__h36937,
	       x__h35224,
	       x__h45591;
  wire IF_IF_fpu_fOperand_S0_first_BIT_195_THEN_IF_fp_ETC___d126,
       IF_NOT_fpu_fState_S3_first__99_BITS_12_TO_0_05_ETC___d707,
       IF_NOT_fpu_fState_S3_first__99_BITS_12_TO_0_05_ETC___d710,
       IF_fpu_fOperand_S0_first_BIT_195_THEN_IF_fpu_f_ETC___d131,
       IF_fpu_fOperand_S0_first_BIT_195_THEN_IF_fpu_f_ETC___d151,
       IF_fpu_fOperand_S0_first_BIT_195_THEN_IF_fpu_f_ETC___d65,
       IF_fpu_fState_S3_first__99_BITS_12_TO_0_05_SLT_ETC___d720,
       IF_fpu_fState_S3_first__99_BITS_12_TO_0_05_SLT_ETC___d725,
       IF_fpu_fState_S8_first__164_BIT_67_167_AND_IF__ETC___d1264,
       NOT_IF_fpu_fOperand_S0_first_BIT_195_THEN_IF_f_ETC___d150,
       NOT_fpu_fOperand_S0_first_BITS_129_TO_119_9_EQ_ETC___d127,
       NOT_fpu_fOperand_S0_first_BIT_130_4_EQ_fpu_fOp_ETC___d57,
       NOT_fpu_fState_S3_first__99_BITS_12_TO_0_05_SL_ETC___d714,
       NOT_fpu_fState_S4_first__51_BIT_130_57_62_OR_N_ETC___d788,
       _0_CONCAT_IF_IF_7170_MINUS_fpu_fState_S3_first__ETC___d667,
       _0_CONCAT_IF_IF_fpu_fState_S7_first__55_BIT_128_ETC___d1108,
       _7170_MINUS_fpu_fState_S3_first__99_BITS_12_TO__ETC___d212,
       fpu_fOperand_S0_first_BITS_129_TO_119_9_EQ_204_ETC___d130,
       fpu_fOperand_S0_first_BITS_129_TO_119_9_EQ_204_ETC___d60,
       fpu_fOperand_S0_first_BIT_195_AND_fpu_fOperand_ETC___d58,
       fpu_fState_S3_first__99_BITS_12_TO_0_05_SLE_1023___d206,
       fpu_fState_S3_first__99_BITS_12_TO_0_05_SLT_7116___d208,
       sfdlsb__h20642;

  // action method request_put
  assign RDY_request_put = fpu_fOperand_S0$FULL_N ;
  assign CAN_FIRE_request_put = fpu_fOperand_S0$FULL_N ;
  assign WILL_FIRE_request_put = EN_request_put ;

  // actionvalue method response_get
  assign response_get = fpu_fResult_S9$D_OUT ;
  assign RDY_response_get = fpu_fResult_S9$EMPTY_N ;
  assign CAN_FIRE_response_get = fpu_fResult_S9$EMPTY_N ;
  assign WILL_FIRE_response_get = EN_response_get ;

  // submodule fpu_fOperand_S0
  FIFOL1 #(.width(32'd196)) fpu_fOperand_S0(.RST(RST_N),
					    .CLK(CLK),
					    .D_IN(fpu_fOperand_S0$D_IN),
					    .ENQ(fpu_fOperand_S0$ENQ),
					    .DEQ(fpu_fOperand_S0$DEQ),
					    .CLR(fpu_fOperand_S0$CLR),
					    .D_OUT(fpu_fOperand_S0$D_OUT),
					    .FULL_N(fpu_fOperand_S0$FULL_N),
					    .EMPTY_N(fpu_fOperand_S0$EMPTY_N));

  // submodule fpu_fProd_S2
  FIFOL1 #(.width(32'd106)) fpu_fProd_S2(.RST(RST_N),
					 .CLK(CLK),
					 .D_IN(fpu_fProd_S2$D_IN),
					 .ENQ(fpu_fProd_S2$ENQ),
					 .DEQ(fpu_fProd_S2$DEQ),
					 .CLR(fpu_fProd_S2$CLR),
					 .D_OUT(fpu_fProd_S2$D_OUT),
					 .FULL_N(fpu_fProd_S2$FULL_N),
					 .EMPTY_N(fpu_fProd_S2$EMPTY_N));

  // submodule fpu_fProd_S3
  FIFOL1 #(.width(32'd106)) fpu_fProd_S3(.RST(RST_N),
					 .CLK(CLK),
					 .D_IN(fpu_fProd_S3$D_IN),
					 .ENQ(fpu_fProd_S3$ENQ),
					 .DEQ(fpu_fProd_S3$DEQ),
					 .CLR(fpu_fProd_S3$CLR),
					 .D_OUT(fpu_fProd_S3$D_OUT),
					 .FULL_N(fpu_fProd_S3$FULL_N),
					 .EMPTY_N(fpu_fProd_S3$EMPTY_N));

  // submodule fpu_fResult_S9
  FIFOL1 #(.width(32'd69)) fpu_fResult_S9(.RST(RST_N),
					  .CLK(CLK),
					  .D_IN(fpu_fResult_S9$D_IN),
					  .ENQ(fpu_fResult_S9$ENQ),
					  .DEQ(fpu_fResult_S9$DEQ),
					  .CLR(fpu_fResult_S9$CLR),
					  .D_OUT(fpu_fResult_S9$D_OUT),
					  .FULL_N(fpu_fResult_S9$FULL_N),
					  .EMPTY_N(fpu_fResult_S9$EMPTY_N));

  // submodule fpu_fState_S1
  FIFOL1 #(.width(32'd258)) fpu_fState_S1(.RST(RST_N),
					  .CLK(CLK),
					  .D_IN(fpu_fState_S1$D_IN),
					  .ENQ(fpu_fState_S1$ENQ),
					  .DEQ(fpu_fState_S1$DEQ),
					  .CLR(fpu_fState_S1$CLR),
					  .D_OUT(fpu_fState_S1$D_OUT),
					  .FULL_N(fpu_fState_S1$FULL_N),
					  .EMPTY_N(fpu_fState_S1$EMPTY_N));

  // submodule fpu_fState_S2
  FIFOL1 #(.width(32'd152)) fpu_fState_S2(.RST(RST_N),
					  .CLK(CLK),
					  .D_IN(fpu_fState_S2$D_IN),
					  .ENQ(fpu_fState_S2$ENQ),
					  .DEQ(fpu_fState_S2$DEQ),
					  .CLR(fpu_fState_S2$CLR),
					  .D_OUT(fpu_fState_S2$D_OUT),
					  .FULL_N(fpu_fState_S2$FULL_N),
					  .EMPTY_N(fpu_fState_S2$EMPTY_N));

  // submodule fpu_fState_S3
  FIFOL1 #(.width(32'd152)) fpu_fState_S3(.RST(RST_N),
					  .CLK(CLK),
					  .D_IN(fpu_fState_S3$D_IN),
					  .ENQ(fpu_fState_S3$ENQ),
					  .DEQ(fpu_fState_S3$DEQ),
					  .CLR(fpu_fState_S3$CLR),
					  .D_OUT(fpu_fState_S3$D_OUT),
					  .FULL_N(fpu_fState_S3$FULL_N),
					  .EMPTY_N(fpu_fState_S3$EMPTY_N));

  // submodule fpu_fState_S4
  FIFOL1 #(.width(32'd204)) fpu_fState_S4(.RST(RST_N),
					  .CLK(CLK),
					  .D_IN(fpu_fState_S4$D_IN),
					  .ENQ(fpu_fState_S4$ENQ),
					  .DEQ(fpu_fState_S4$DEQ),
					  .CLR(fpu_fState_S4$CLR),
					  .D_OUT(fpu_fState_S4$D_OUT),
					  .FULL_N(fpu_fState_S4$FULL_N),
					  .EMPTY_N(fpu_fState_S4$EMPTY_N));

  // submodule fpu_fState_S5
  FIFOL1 #(.width(32'd216)) fpu_fState_S5(.RST(RST_N),
					  .CLK(CLK),
					  .D_IN(fpu_fState_S5$D_IN),
					  .ENQ(fpu_fState_S5$ENQ),
					  .DEQ(fpu_fState_S5$DEQ),
					  .CLR(fpu_fState_S5$CLR),
					  .D_OUT(fpu_fState_S5$D_OUT),
					  .FULL_N(fpu_fState_S5$FULL_N),
					  .EMPTY_N(fpu_fState_S5$EMPTY_N));

  // submodule fpu_fState_S6
  FIFOL1 #(.width(32'd203)) fpu_fState_S6(.RST(RST_N),
					  .CLK(CLK),
					  .D_IN(fpu_fState_S6$D_IN),
					  .ENQ(fpu_fState_S6$ENQ),
					  .DEQ(fpu_fState_S6$DEQ),
					  .CLR(fpu_fState_S6$CLR),
					  .D_OUT(fpu_fState_S6$D_OUT),
					  .FULL_N(fpu_fState_S6$FULL_N),
					  .EMPTY_N(fpu_fState_S6$EMPTY_N));

  // submodule fpu_fState_S7
  FIFOL1 #(.width(32'd203)) fpu_fState_S7(.RST(RST_N),
					  .CLK(CLK),
					  .D_IN(fpu_fState_S7$D_IN),
					  .ENQ(fpu_fState_S7$ENQ),
					  .DEQ(fpu_fState_S7$DEQ),
					  .CLR(fpu_fState_S7$CLR),
					  .D_OUT(fpu_fState_S7$D_OUT),
					  .FULL_N(fpu_fState_S7$FULL_N),
					  .EMPTY_N(fpu_fState_S7$EMPTY_N));

  // submodule fpu_fState_S8
  FIFOL1 #(.width(32'd141)) fpu_fState_S8(.RST(RST_N),
					  .CLK(CLK),
					  .D_IN(fpu_fState_S8$D_IN),
					  .ENQ(fpu_fState_S8$ENQ),
					  .DEQ(fpu_fState_S8$DEQ),
					  .CLR(fpu_fState_S8$CLR),
					  .D_OUT(fpu_fState_S8$D_OUT),
					  .FULL_N(fpu_fState_S8$FULL_N),
					  .EMPTY_N(fpu_fState_S8$EMPTY_N));

  // rule RL_fpu_s9_stage
  assign CAN_FIRE_RL_fpu_s9_stage =
	     fpu_fState_S8$EMPTY_N && fpu_fResult_S9$FULL_N ;
  assign WILL_FIRE_RL_fpu_s9_stage = CAN_FIRE_RL_fpu_s9_stage ;

  // rule RL_fpu_s8_stage
  assign CAN_FIRE_RL_fpu_s8_stage =
	     fpu_fState_S7$EMPTY_N && fpu_fState_S8$FULL_N ;
  assign WILL_FIRE_RL_fpu_s8_stage = CAN_FIRE_RL_fpu_s8_stage ;

  // rule RL_fpu_s7_stage
  assign CAN_FIRE_RL_fpu_s7_stage =
	     fpu_fState_S6$EMPTY_N && fpu_fState_S7$FULL_N ;
  assign WILL_FIRE_RL_fpu_s7_stage = CAN_FIRE_RL_fpu_s7_stage ;

  // rule RL_fpu_s6_stage
  assign CAN_FIRE_RL_fpu_s6_stage =
	     fpu_fState_S5$EMPTY_N && fpu_fState_S6$FULL_N ;
  assign WILL_FIRE_RL_fpu_s6_stage = CAN_FIRE_RL_fpu_s6_stage ;

  // rule RL_fpu_s5_stage
  assign CAN_FIRE_RL_fpu_s5_stage =
	     fpu_fState_S4$EMPTY_N && fpu_fState_S5$FULL_N ;
  assign WILL_FIRE_RL_fpu_s5_stage = CAN_FIRE_RL_fpu_s5_stage ;

  // rule RL_fpu_s4_stage
  assign CAN_FIRE_RL_fpu_s4_stage =
	     fpu_fState_S3$EMPTY_N && fpu_fProd_S3$EMPTY_N &&
	     fpu_fState_S4$FULL_N ;
  assign WILL_FIRE_RL_fpu_s4_stage = CAN_FIRE_RL_fpu_s4_stage ;

  // rule RL_fpu_s3_stage
  assign CAN_FIRE_RL_fpu_s3_stage =
	     fpu_fState_S2$EMPTY_N && fpu_fProd_S2$EMPTY_N &&
	     fpu_fProd_S3$FULL_N &&
	     fpu_fState_S3$FULL_N ;
  assign WILL_FIRE_RL_fpu_s3_stage = CAN_FIRE_RL_fpu_s3_stage ;

  // rule RL_fpu_s2_stage
  assign CAN_FIRE_RL_fpu_s2_stage =
	     fpu_fState_S1$EMPTY_N && fpu_fProd_S2$FULL_N &&
	     fpu_fState_S2$FULL_N ;
  assign WILL_FIRE_RL_fpu_s2_stage = CAN_FIRE_RL_fpu_s2_stage ;

  // rule RL_fpu_s1_stage
  assign CAN_FIRE_RL_fpu_s1_stage =
	     fpu_fOperand_S0$EMPTY_N && fpu_fState_S1$FULL_N ;
  assign WILL_FIRE_RL_fpu_s1_stage = CAN_FIRE_RL_fpu_s1_stage ;

  // submodule fpu_fOperand_S0
  assign fpu_fOperand_S0$D_IN = request_put ;
  assign fpu_fOperand_S0$ENQ = EN_request_put ;
  assign fpu_fOperand_S0$DEQ = CAN_FIRE_RL_fpu_s1_stage ;
  assign fpu_fOperand_S0$CLR = 1'b0 ;

  // submodule fpu_fProd_S2
  assign fpu_fProd_S2$D_IN =
	     fpu_fState_S1$D_OUT[105:53] * fpu_fState_S1$D_OUT[52:0] ;
  assign fpu_fProd_S2$ENQ = CAN_FIRE_RL_fpu_s2_stage ;
  assign fpu_fProd_S2$DEQ = CAN_FIRE_RL_fpu_s3_stage ;
  assign fpu_fProd_S2$CLR = 1'b0 ;

  // submodule fpu_fProd_S3
  assign fpu_fProd_S3$D_IN = fpu_fProd_S2$D_OUT ;
  assign fpu_fProd_S3$ENQ = CAN_FIRE_RL_fpu_s3_stage ;
  assign fpu_fProd_S3$DEQ = CAN_FIRE_RL_fpu_s4_stage ;
  assign fpu_fProd_S3$CLR = 1'b0 ;

  // submodule fpu_fResult_S9
  assign fpu_fResult_S9$D_IN =
	     fpu_fState_S8$D_OUT[140] ?
	       fpu_fState_S8$D_OUT[139:71] :
	       IF_fpu_fState_S8_first__164_BIT_67_167_AND_IF__ETC___d1285 ;
  assign fpu_fResult_S9$ENQ = CAN_FIRE_RL_fpu_s9_stage ;
  assign fpu_fResult_S9$DEQ = EN_response_get ;
  assign fpu_fResult_S9$CLR = 1'b0 ;

  // submodule fpu_fState_S1
  assign fpu_fState_S1$D_IN =
	     { x__h321 == 11'd2047 && _theResult___fst_sfd__h394 != 52'd0 &&
	       !_theResult___fst_sfd__h394[51] ||
	       fpu_fOperand_S0$D_OUT[129:119] == 11'd2047 &&
	       fpu_fOperand_S0$D_OUT[118:67] != 52'd0 &&
	       !fpu_fOperand_S0$D_OUT[118] ||
	       fpu_fOperand_S0$D_OUT[65:55] == 11'd2047 &&
	       fpu_fOperand_S0$D_OUT[54:3] != 52'd0 &&
	       !fpu_fOperand_S0$D_OUT[54] ||
	       IF_fpu_fOperand_S0_first_BIT_195_THEN_IF_fpu_f_ETC___d65,
	       IF_IF_fpu_fOperand_S0_first_BIT_195_THEN_IF_fp_ETC___d143,
	       IF_fpu_fOperand_S0_first_BIT_195_THEN_IF_fpu_f_ETC___d151,
	       4'd0,
	       fpu_fOperand_S0$D_OUT[2:0],
	       fpu_fOperand_S0$D_OUT[195],
	       fpu_fOperand_S0$D_OUT[195] && fpu_fOperand_S0$D_OUT[194],
	       IF_fpu_fOperand_S0_first_BIT_195_THEN_fpu_fOpe_ETC___d115,
	       NOT_fpu_fOperand_S0_first_BIT_130_4_EQ_fpu_fOp_ETC___d57,
	       IF_fpu_fOperand_S0_first_BITS_129_TO_119_9_EQ__ETC___d163 } ;
  assign fpu_fState_S1$ENQ = CAN_FIRE_RL_fpu_s1_stage ;
  assign fpu_fState_S1$DEQ = CAN_FIRE_RL_fpu_s2_stage ;
  assign fpu_fState_S1$CLR = 1'b0 ;

  // submodule fpu_fState_S2
  assign fpu_fState_S2$D_IN = fpu_fState_S1$D_OUT[257:106] ;
  assign fpu_fState_S2$ENQ = CAN_FIRE_RL_fpu_s2_stage ;
  assign fpu_fState_S2$DEQ = CAN_FIRE_RL_fpu_s3_stage ;
  assign fpu_fState_S2$CLR = 1'b0 ;

  // submodule fpu_fState_S3
  assign fpu_fState_S3$D_IN = fpu_fState_S2$D_OUT ;
  assign fpu_fState_S3$ENQ = CAN_FIRE_RL_fpu_s3_stage ;
  assign fpu_fState_S3$DEQ = CAN_FIRE_RL_fpu_s4_stage ;
  assign fpu_fState_S3$CLR = 1'b0 ;

  // submodule fpu_fState_S4
  assign fpu_fState_S4$D_IN =
	     { fpu_fState_S3$D_OUT[151:87],
	       IF_fpu_fState_S3_first__99_BIT_151_00_THEN_fpu_ETC___d729,
	       fpu_fState_S3$D_OUT[81:14],
	       !fpu_fState_S3$D_OUT[151] && fpu_fState_S3$D_OUT[13],
	       fpu_fState_S3$D_OUT[151] ?
		 63'd0 :
		 IF_fpu_fState_S3_first__99_BITS_12_TO_0_05_SLE_ETC___d740,
	       x__h35224 } ;
  assign fpu_fState_S4$ENQ = CAN_FIRE_RL_fpu_s4_stage ;
  assign fpu_fState_S4$DEQ = CAN_FIRE_RL_fpu_s5_stage ;
  assign fpu_fState_S4$CLR = 1'b0 ;

  // submodule fpu_fState_S5
  assign fpu_fState_S5$D_IN =
	     { fpu_fState_S4$D_OUT[203:130],
	       fpu_fState_S4$D_OUT[129] != fpu_fState_S4$D_OUT[65],
	       NOT_fpu_fState_S4_first__51_BIT_130_57_62_OR_N_ETC___d788 ?
		 fpu_fState_S4$D_OUT[65] :
		 fpu_fState_S4$D_OUT[129],
	       IF_NOT_fpu_fState_S4_first__51_BIT_130_57_62_O_ETC___d799 } ;
  assign fpu_fState_S5$ENQ = CAN_FIRE_RL_fpu_s5_stage ;
  assign fpu_fState_S5$DEQ = CAN_FIRE_RL_fpu_s6_stage ;
  assign fpu_fState_S5$CLR = 1'b0 ;

  // submodule fpu_fState_S6
  assign fpu_fState_S6$D_IN =
	     { fpu_fState_S5$D_OUT[215:127],
	       fpu_fState_S5$D_OUT[113:57],
	       x__h36183 } ;
  assign fpu_fState_S6$ENQ = CAN_FIRE_RL_fpu_s6_stage ;
  assign fpu_fState_S6$DEQ = CAN_FIRE_RL_fpu_s7_stage ;
  assign fpu_fState_S6$CLR = 1'b0 ;

  // submodule fpu_fState_S7
  assign fpu_fState_S7$D_IN =
	     { fpu_fState_S6$D_OUT[202:114], x__h36698, x__h36707 } ;
  assign fpu_fState_S7$ENQ = CAN_FIRE_RL_fpu_s7_stage ;
  assign fpu_fState_S7$DEQ = CAN_FIRE_RL_fpu_s8_stage ;
  assign fpu_fState_S7$CLR = 1'b0 ;

  // submodule fpu_fState_S8
  assign fpu_fState_S8$D_IN =
	     { fpu_fState_S7$D_OUT[202:138],
	       fpu_fState_S7$D_OUT[202] ?
		 fpu_fState_S7$D_OUT[137:133] :
		 fpu_fState_S7_first__55_BITS_137_TO_133_60_OR__ETC___d1146,
	       fpu_fState_S7$D_OUT[132:129],
	       !fpu_fState_S7$D_OUT[202] && fpu_fState_S7$D_OUT[127],
	       fpu_fState_S7$D_OUT[202] ?
		 63'd0 :
		 IF_IF_fpu_fState_S7_first__55_BIT_128_61_THEN__ETC___d1156,
	       x__h45591,
	       fpu_fState_S7$D_OUT[128] } ;
  assign fpu_fState_S8$ENQ = CAN_FIRE_RL_fpu_s8_stage ;
  assign fpu_fState_S8$DEQ = CAN_FIRE_RL_fpu_s9_stage ;
  assign fpu_fState_S8$CLR = 1'b0 ;

  // remaining internal signals
  assign IF_0_CONCAT_IF_IF_7170_MINUS_fpu_fState_S3_fir_ETC__q4 =
	     _0_CONCAT_IF_IF_7170_MINUS_fpu_fState_S3_first__ETC___d667 ?
	       _theResult___snd__h34841 :
	       _theResult___snd__h34836 ;
  assign IF_0_CONCAT_IF_IF_fpu_fState_S7_first__55_BIT__ETC__q9 =
	     _0_CONCAT_IF_IF_fpu_fState_S7_first__55_BIT_128_ETC___d1108 ?
	       _theResult___snd__h45280 :
	       _theResult___snd__h45275 ;
  assign IF_0b0_CONCAT_NOT_fpu_fState_S8_first__164_BIT_ETC___d1269 =
	     sfd__h45862[53] ?
	       ((fpu_fState_S8$D_OUT[65:55] == 11'd2046) ?
		  63'h7FF0000000000000 :
		  { din_inc___2_exp__h46451, sfd__h45862[52:1] }) :
	       { IF_fpu_fState_S8_first__164_BITS_65_TO_55_168__ETC___d1190,
		 sfd__h45862[51:0] } ;
  assign IF_IF_7170_MINUS_fpu_fState_S3_first__99_BITS__ETC___d235 =
	     (din_exp__h34684 == 11'd0) ?
	       12'd3074 :
	       { din_exp4684_MINUS_1023__q3[10],
		 din_exp4684_MINUS_1023__q3 } ;
  assign IF_IF_7170_MINUS_fpu_fState_S3_first__99_BITS__ETC___d664 =
	     (sfdBC__h19463[105] ?
		7'd0 :
		(sfdBC__h19463[104] ?
		   7'd1 :
		   (sfdBC__h19463[103] ?
		      7'd2 :
		      (sfdBC__h19463[102] ?
			 7'd3 :
			 (sfdBC__h19463[101] ?
			    7'd4 :
			    (sfdBC__h19463[100] ?
			       7'd5 :
			       (sfdBC__h19463[99] ?
				  7'd6 :
				  (sfdBC__h19463[98] ?
				     7'd7 :
				     (sfdBC__h19463[97] ?
					7'd8 :
					(sfdBC__h19463[96] ?
					   7'd9 :
					   (sfdBC__h19463[95] ?
					      7'd10 :
					      (sfdBC__h19463[94] ?
						 7'd11 :
						 (sfdBC__h19463[93] ?
						    7'd12 :
						    (sfdBC__h19463[92] ?
						       7'd13 :
						       (sfdBC__h19463[91] ?
							  7'd14 :
							  (sfdBC__h19463[90] ?
							     7'd15 :
							     (sfdBC__h19463[89] ?
								7'd16 :
								(sfdBC__h19463[88] ?
								   7'd17 :
								   (sfdBC__h19463[87] ?
								      7'd18 :
								      (sfdBC__h19463[86] ?
									 7'd19 :
									 (sfdBC__h19463[85] ?
									    7'd20 :
									    (sfdBC__h19463[84] ?
									       7'd21 :
									       (sfdBC__h19463[83] ?
										  7'd22 :
										  (sfdBC__h19463[82] ?
										     7'd23 :
										     (sfdBC__h19463[81] ?
											7'd24 :
											(sfdBC__h19463[80] ?
											   7'd25 :
											   (sfdBC__h19463[79] ?
											      7'd26 :
											      (sfdBC__h19463[78] ?
												 7'd27 :
												 (sfdBC__h19463[77] ?
												    7'd28 :
												    (sfdBC__h19463[76] ?
												       7'd29 :
												       (sfdBC__h19463[75] ?
													  7'd30 :
													  (sfdBC__h19463[74] ?
													     7'd31 :
													     (sfdBC__h19463[73] ?
														7'd32 :
														(sfdBC__h19463[72] ?
														   7'd33 :
														   (sfdBC__h19463[71] ?
														      7'd34 :
														      (sfdBC__h19463[70] ?
															 7'd35 :
															 (sfdBC__h19463[69] ?
															    7'd36 :
															    (sfdBC__h19463[68] ?
															       7'd37 :
															       (sfdBC__h19463[67] ?
																  7'd38 :
																  (sfdBC__h19463[66] ?
																     7'd39 :
																     (sfdBC__h19463[65] ?
																	7'd40 :
																	(sfdBC__h19463[64] ?
																	   7'd41 :
																	   (sfdBC__h19463[63] ?
																	      7'd42 :
																	      (sfdBC__h19463[62] ?
																		 7'd43 :
																		 (sfdBC__h19463[61] ?
																		    7'd44 :
																		    (sfdBC__h19463[60] ?
																		       7'd45 :
																		       (sfdBC__h19463[59] ?
																			  7'd46 :
																			  (sfdBC__h19463[58] ?
																			     7'd47 :
																			     (sfdBC__h19463[57] ?
																				7'd48 :
																				(sfdBC__h19463[56] ?
																				   7'd49 :
																				   (sfdBC__h19463[55] ?
																				      7'd50 :
																				      (sfdBC__h19463[54] ?
																					 7'd51 :
																					 (sfdBC__h19463[53] ?
																					    7'd52 :
																					    (sfdBC__h19463[52] ?
																					       7'd53 :
																					       (sfdBC__h19463[51] ?
																						  7'd54 :
																						  (sfdBC__h19463[50] ?
																						     7'd55 :
																						     (sfdBC__h19463[49] ?
																							7'd56 :
																							(sfdBC__h19463[48] ?
																							   7'd57 :
																							   (sfdBC__h19463[47] ?
																							      7'd58 :
																							      (sfdBC__h19463[46] ?
																								 7'd59 :
																								 (sfdBC__h19463[45] ?
																								    7'd60 :
																								    (sfdBC__h19463[44] ?
																								       7'd61 :
																								       (sfdBC__h19463[43] ?
																									  7'd62 :
																									  (sfdBC__h19463[42] ?
																									     7'd63 :
																									     (sfdBC__h19463[41] ?
																										7'd64 :
																										(sfdBC__h19463[40] ?
																										   7'd65 :
																										   (sfdBC__h19463[39] ?
																										      7'd66 :
																										      (sfdBC__h19463[38] ?
																											 7'd67 :
																											 (sfdBC__h19463[37] ?
																											    7'd68 :
																											    (sfdBC__h19463[36] ?
																											       7'd69 :
																											       (sfdBC__h19463[35] ?
																												  7'd70 :
																												  (sfdBC__h19463[34] ?
																												     7'd71 :
																												     (sfdBC__h19463[33] ?
																													7'd72 :
																													(sfdBC__h19463[32] ?
																													   7'd73 :
																													   (sfdBC__h19463[31] ?
																													      7'd74 :
																													      (sfdBC__h19463[30] ?
																														 7'd75 :
																														 (sfdBC__h19463[29] ?
																														    7'd76 :
																														    (sfdBC__h19463[28] ?
																														       7'd77 :
																														       (sfdBC__h19463[27] ?
																															  7'd78 :
																															  (sfdBC__h19463[26] ?
																															     7'd79 :
																															     (sfdBC__h19463[25] ?
																																7'd80 :
																																(sfdBC__h19463[24] ?
																																   7'd81 :
																																   (sfdBC__h19463[23] ?
																																      7'd82 :
																																      (sfdBC__h19463[22] ?
																																	 7'd83 :
																																	 (sfdBC__h19463[21] ?
																																	    7'd84 :
																																	    (sfdBC__h19463[20] ?
																																	       7'd85 :
																																	       (sfdBC__h19463[19] ?
																																		  7'd86 :
																																		  (sfdBC__h19463[18] ?
																																		     7'd87 :
																																		     (sfdBC__h19463[17] ?
																																			7'd88 :
																																			(sfdBC__h19463[16] ?
																																			   7'd89 :
																																			   (sfdBC__h19463[15] ?
																																			      7'd90 :
																																			      (sfdBC__h19463[14] ?
																																				 7'd91 :
																																				 (sfdBC__h19463[13] ?
																																				    7'd92 :
																																				    (sfdBC__h19463[12] ?
																																				       7'd93 :
																																				       (sfdBC__h19463[11] ?
																																					  7'd94 :
																																					  (sfdBC__h19463[10] ?
																																					     7'd95 :
																																					     (sfdBC__h19463[9] ?
																																						7'd96 :
																																						(sfdBC__h19463[8] ?
																																						   7'd97 :
																																						   (sfdBC__h19463[7] ?
																																						      7'd98 :
																																						      (sfdBC__h19463[6] ?
																																							 7'd99 :
																																							 (sfdBC__h19463[5] ?
																																							    7'd100 :
																																							    (sfdBC__h19463[4] ?
																																							       7'd101 :
																																							       (sfdBC__h19463[3] ?
																																								  7'd102 :
																																								  (sfdBC__h19463[2] ?
																																								     7'd103 :
																																								     (sfdBC__h19463[1] ?
																																									7'd104 :
																																									(sfdBC__h19463[0] ?
																																									   7'd105 :
																																									   7'd106)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))) -
	     7'd1 ;
  assign IF_IF_7170_MINUS_fpu_fState_S3_first__99_BITS__ETC___d666 =
	     IF_IF_7170_MINUS_fpu_fState_S3_first__99_BITS__ETC___d235 -
	     12'd3074 ;
  assign IF_IF_7170_MINUS_fpu_fState_S3_first__99_BITS__ETC___d738 =
	     (sfdBC__h19463[105] &&
	      IF_IF_7170_MINUS_fpu_fState_S3_first__99_BITS__ETC___d235 ==
	      12'd1023) ?
	       63'h7FEFFFFFFFFFFFFF :
	       { _theResult___fst_exp__h34767, sfdin__h34761[105:54] } ;
  assign IF_IF_fpu_fOperand_S0_first_BIT_195_THEN_IF_fp_ETC___d126 =
	     (x__h321 == 11'd2047 && _theResult___fst_sfd__h394 == 52'd0) ?
	       fpu_fOperand_S0$D_OUT[195] && fpu_fOperand_S0$D_OUT[194] :
	       ((fpu_fOperand_S0$D_OUT[129:119] == 11'd2047 &&
		 fpu_fOperand_S0$D_OUT[118:67] == 52'd0 ||
		 fpu_fOperand_S0$D_OUT[65:55] == 11'd2047 &&
		 fpu_fOperand_S0$D_OUT[54:3] == 52'd0) ?
		  NOT_fpu_fOperand_S0_first_BIT_130_4_EQ_fpu_fOp_ETC___d57 :
		  fpu_fOperand_S0$D_OUT[195] && fpu_fOperand_S0$D_OUT[194]) ;
  assign IF_IF_fpu_fOperand_S0_first_BIT_195_THEN_IF_fp_ETC___d135 =
	     (x__h321 == 11'd2047 && _theResult___fst_sfd__h394 == 52'd0) ?
	       IF_fpu_fOperand_S0_first_BIT_195_THEN_fpu_fOpe_ETC___d115 :
	       ((fpu_fOperand_S0$D_OUT[129:119] == 11'd2047 &&
		 fpu_fOperand_S0$D_OUT[118:67] == 52'd0 ||
		 fpu_fOperand_S0$D_OUT[65:55] == 11'd2047 &&
		 fpu_fOperand_S0$D_OUT[54:3] == 52'd0) ?
		  63'h7FF0000000000000 :
		  IF_fpu_fOperand_S0_first_BIT_195_THEN_fpu_fOpe_ETC___d115) ;
  assign IF_IF_fpu_fOperand_S0_first_BIT_195_THEN_IF_fp_ETC___d140 =
	     (x__h321 == 11'd2047 && _theResult___fst_sfd__h394[51]) ?
	       { fpu_fOperand_S0$D_OUT[195] && fpu_fOperand_S0$D_OUT[194],
		 IF_fpu_fOperand_S0_first_BIT_195_THEN_fpu_fOpe_ETC___d115 } :
	       ((fpu_fOperand_S0$D_OUT[129:119] == 11'd2047 &&
		 fpu_fOperand_S0$D_OUT[118]) ?
		  fpu_fOperand_S0$D_OUT[130:67] :
		  ((fpu_fOperand_S0$D_OUT[65:55] == 11'd2047 &&
		    fpu_fOperand_S0$D_OUT[54]) ?
		     fpu_fOperand_S0$D_OUT[66:3] :
		     { NOT_fpu_fOperand_S0_first_BITS_129_TO_119_9_EQ_ETC___d127,
		       IF_fpu_fOperand_S0_first_BITS_129_TO_119_9_EQ__ETC___d136 })) ;
  assign IF_IF_fpu_fOperand_S0_first_BIT_195_THEN_IF_fp_ETC___d143 =
	     (x__h321 == 11'd2047 && _theResult___fst_sfd__h394 != 52'd0 &&
	      !_theResult___fst_sfd__h394[51]) ?
	       { fpu_fOperand_S0$D_OUT[195] && fpu_fOperand_S0$D_OUT[194],
		 x__h321,
		 sfd__h3217 } :
	       IF_fpu_fOperand_S0_first_BITS_129_TO_119_9_EQ__ETC___d142 ;
  assign IF_IF_fpu_fState_S7_first__55_BIT_128_61_THEN__ETC___d1105 =
	     (sfd__h36933[56] ?
		6'd0 :
		(sfd__h36933[55] ?
		   6'd1 :
		   (sfd__h36933[54] ?
		      6'd2 :
		      (sfd__h36933[53] ?
			 6'd3 :
			 (sfd__h36933[52] ?
			    6'd4 :
			    (sfd__h36933[51] ?
			       6'd5 :
			       (sfd__h36933[50] ?
				  6'd6 :
				  (sfd__h36933[49] ?
				     6'd7 :
				     (sfd__h36933[48] ?
					6'd8 :
					(sfd__h36933[47] ?
					   6'd9 :
					   (sfd__h36933[46] ?
					      6'd10 :
					      (sfd__h36933[45] ?
						 6'd11 :
						 (sfd__h36933[44] ?
						    6'd12 :
						    (sfd__h36933[43] ?
						       6'd13 :
						       (sfd__h36933[42] ?
							  6'd14 :
							  (sfd__h36933[41] ?
							     6'd15 :
							     (sfd__h36933[40] ?
								6'd16 :
								(sfd__h36933[39] ?
								   6'd17 :
								   (sfd__h36933[38] ?
								      6'd18 :
								      (sfd__h36933[37] ?
									 6'd19 :
									 (sfd__h36933[36] ?
									    6'd20 :
									    (sfd__h36933[35] ?
									       6'd21 :
									       (sfd__h36933[34] ?
										  6'd22 :
										  (sfd__h36933[33] ?
										     6'd23 :
										     (sfd__h36933[32] ?
											6'd24 :
											(sfd__h36933[31] ?
											   6'd25 :
											   (sfd__h36933[30] ?
											      6'd26 :
											      (sfd__h36933[29] ?
												 6'd27 :
												 (sfd__h36933[28] ?
												    6'd28 :
												    (sfd__h36933[27] ?
												       6'd29 :
												       (sfd__h36933[26] ?
													  6'd30 :
													  (sfd__h36933[25] ?
													     6'd31 :
													     (sfd__h36933[24] ?
														6'd32 :
														(sfd__h36933[23] ?
														   6'd33 :
														   (sfd__h36933[22] ?
														      6'd34 :
														      (sfd__h36933[21] ?
															 6'd35 :
															 (sfd__h36933[20] ?
															    6'd36 :
															    (sfd__h36933[19] ?
															       6'd37 :
															       (sfd__h36933[18] ?
																  6'd38 :
																  (sfd__h36933[17] ?
																     6'd39 :
																     (sfd__h36933[16] ?
																	6'd40 :
																	(sfd__h36933[15] ?
																	   6'd41 :
																	   (sfd__h36933[14] ?
																	      6'd42 :
																	      (sfd__h36933[13] ?
																		 6'd43 :
																		 (sfd__h36933[12] ?
																		    6'd44 :
																		    (sfd__h36933[11] ?
																		       6'd45 :
																		       (sfd__h36933[10] ?
																			  6'd46 :
																			  (sfd__h36933[9] ?
																			     6'd47 :
																			     (sfd__h36933[8] ?
																				6'd48 :
																				(sfd__h36933[7] ?
																				   6'd49 :
																				   (sfd__h36933[6] ?
																				      6'd50 :
																				      (sfd__h36933[5] ?
																					 6'd51 :
																					 (sfd__h36933[4] ?
																					    6'd52 :
																					    (sfd__h36933[3] ?
																					       6'd53 :
																					       (sfd__h36933[2] ?
																						  6'd54 :
																						  (sfd__h36933[1] ?
																						     6'd55 :
																						     (sfd__h36933[0] ?
																							6'd56 :
																							6'd57))))))))))))))))))))))))))))))))))))))))))))))))))))))))) -
	     6'd1 ;
  assign IF_IF_fpu_fState_S7_first__55_BIT_128_61_THEN__ETC___d1156 =
	     (sfd__h36933[56] &&
	      IF_fpu_fState_S7_first__55_BITS_126_TO_114_66__ETC___d872 ==
	      12'd1023) ?
	       63'h7FEFFFFFFFFFFFFF :
	       { _theResult___fst_exp__h45206, sfdin__h45200[56:5] } ;
  assign IF_NOT_fpu_fState_S3_first__99_BITS_12_TO_0_05_ETC___d707 =
	     (!fpu_fState_S3_first__99_BITS_12_TO_0_05_SLE_1023___d206 ||
	      fpu_fState_S3_first__99_BITS_12_TO_0_05_SLT_7116___d208) ?
	       fpu_fState_S3$D_OUT[86] :
	       fpu_fState_S3_first__99_BITS_86_TO_82_04_OR_0__ETC___d705[4] ;
  assign IF_NOT_fpu_fState_S3_first__99_BITS_12_TO_0_05_ETC___d710 =
	     (!fpu_fState_S3_first__99_BITS_12_TO_0_05_SLE_1023___d206 ||
	      fpu_fState_S3_first__99_BITS_12_TO_0_05_SLT_7116___d208) ?
	       fpu_fState_S3$D_OUT[85] :
	       fpu_fState_S3_first__99_BITS_86_TO_82_04_OR_0__ETC___d705[3] ;
  assign IF_NOT_fpu_fState_S4_first__51_BIT_130_57_62_O_ETC___d799 =
	     { NOT_fpu_fState_S4_first__51_BIT_130_57_62_OR_N_ETC___d788 ?
		 IF_fpu_fState_S4_first__51_BITS_64_TO_54_63_EQ_ETC___d767 :
		 IF_fpu_fState_S4_first__51_BITS_128_TO_118_68__ETC___d772,
	       NOT_fpu_fState_S4_first__51_BIT_130_57_62_OR_N_ETC___d788 ?
		 IF_fpu_fState_S4_first__51_BITS_64_TO_54_63_EQ_ETC___d767 -
		 IF_fpu_fState_S4_first__51_BITS_128_TO_118_68__ETC___d772 :
		 IF_fpu_fState_S4_first__51_BITS_128_TO_118_68__ETC___d772 -
		 IF_fpu_fState_S4_first__51_BITS_64_TO_54_63_EQ_ETC___d767,
	       x__h35761,
	       x__h35765 } ;
  assign IF_fpu_fOperand_S0_first_BITS_129_TO_119_9_EQ__ETC___d136 =
	     (fpu_fOperand_S0_first_BITS_129_TO_119_9_EQ_204_ETC___d130 ||
	      IF_fpu_fOperand_S0_first_BIT_195_THEN_IF_fpu_f_ETC___d131 &&
	      !fpu_fOperand_S0_first_BIT_195_AND_fpu_fOperand_ETC___d58) ?
	       63'h7FF8000000000000 :
	       IF_IF_fpu_fOperand_S0_first_BIT_195_THEN_IF_fp_ETC___d135 ;
  assign IF_fpu_fOperand_S0_first_BITS_129_TO_119_9_EQ__ETC___d142 =
	     (fpu_fOperand_S0$D_OUT[129:119] == 11'd2047 &&
	      fpu_fOperand_S0$D_OUT[118:67] != 52'd0 &&
	      !fpu_fOperand_S0$D_OUT[118]) ?
	       { fpu_fOperand_S0$D_OUT[130:119], sfd__h3220 } :
	       ((fpu_fOperand_S0$D_OUT[65:55] == 11'd2047 &&
		 fpu_fOperand_S0$D_OUT[54:3] != 52'd0 &&
		 !fpu_fOperand_S0$D_OUT[54]) ?
		  { fpu_fOperand_S0$D_OUT[66:55], sfd__h3223 } :
		  IF_IF_fpu_fOperand_S0_first_BIT_195_THEN_IF_fp_ETC___d140) ;
  assign IF_fpu_fOperand_S0_first_BITS_129_TO_119_9_EQ__ETC___d163 =
	     { ((fpu_fOperand_S0$D_OUT[129:119] == 11'd0) ?
		  13'd7170 :
		  { {2{fpu_fOperand_S0D_OUT_BITS_129_TO_119_MINUS_1023__q15[10]}},
		    fpu_fOperand_S0D_OUT_BITS_129_TO_119_MINUS_1023__q15 }) +
	       ((fpu_fOperand_S0$D_OUT[65:55] == 11'd0) ?
		  13'd7170 :
		  { {2{fpu_fOperand_S0D_OUT_BITS_65_TO_55_MINUS_1023__q16[10]}},
		    fpu_fOperand_S0D_OUT_BITS_65_TO_55_MINUS_1023__q16 }),
	       x__h18075,
	       x__h18087 } ;
  assign IF_fpu_fOperand_S0_first_BIT_195_THEN_IF_fpu_f_ETC___d131 =
	     x__h321 == 11'd2047 && _theResult___fst_sfd__h394 == 52'd0 &&
	     (fpu_fOperand_S0$D_OUT[129:119] == 11'd2047 &&
	      fpu_fOperand_S0$D_OUT[118:67] == 52'd0 ||
	      fpu_fOperand_S0$D_OUT[65:55] == 11'd2047 &&
	      fpu_fOperand_S0$D_OUT[54:3] == 52'd0) ;
  assign IF_fpu_fOperand_S0_first_BIT_195_THEN_IF_fpu_f_ETC___d151 =
	     x__h321 == 11'd2047 && _theResult___fst_sfd__h394 != 52'd0 &&
	     !_theResult___fst_sfd__h394[51] ||
	     fpu_fOperand_S0$D_OUT[129:119] == 11'd2047 &&
	     fpu_fOperand_S0$D_OUT[118:67] != 52'd0 &&
	     !fpu_fOperand_S0$D_OUT[118] ||
	     fpu_fOperand_S0$D_OUT[65:55] == 11'd2047 &&
	     fpu_fOperand_S0$D_OUT[54:3] != 52'd0 &&
	     !fpu_fOperand_S0$D_OUT[54] ||
	     NOT_IF_fpu_fOperand_S0_first_BIT_195_THEN_IF_f_ETC___d150 ;
  assign IF_fpu_fOperand_S0_first_BIT_195_THEN_IF_fpu_f_ETC___d65 =
	     x__h321 == 11'd2047 && _theResult___fst_sfd__h394[51] ||
	     fpu_fOperand_S0$D_OUT[129:119] == 11'd2047 &&
	     fpu_fOperand_S0$D_OUT[118] ||
	     fpu_fOperand_S0$D_OUT[65:55] == 11'd2047 &&
	     fpu_fOperand_S0$D_OUT[54] ||
	     x__h321 == 11'd2047 && _theResult___fst_sfd__h394 == 52'd0 ||
	     fpu_fOperand_S0_first_BITS_129_TO_119_9_EQ_204_ETC___d60 ;
  assign IF_fpu_fOperand_S0_first_BIT_195_THEN_fpu_fOpe_ETC___d115 =
	     fpu_fOperand_S0$D_OUT[195] ?
	       fpu_fOperand_S0$D_OUT[193:131] :
	       63'd0 ;
  assign IF_fpu_fState_S3_first__99_BITS_12_TO_0_05_SLE_ETC___d740 =
	     fpu_fState_S3_first__99_BITS_12_TO_0_05_SLE_1023___d206 ?
	       (fpu_fState_S3_first__99_BITS_12_TO_0_05_SLT_7116___d208 ?
		  63'd0 :
		  IF_IF_7170_MINUS_fpu_fState_S3_first__99_BITS__ETC___d738) :
	       63'h7FEFFFFFFFFFFFFF ;
  assign IF_fpu_fState_S3_first__99_BITS_12_TO_0_05_SLT_ETC___d720 =
	     fpu_fState_S3_first__99_BITS_12_TO_0_05_SLT_7116___d208 ?
	       fpu_fProd_S3$D_OUT != 106'd0 || fpu_fState_S3$D_OUT[83] :
	       fpu_fState_S3_first__99_BITS_86_TO_82_04_OR_0__ETC___d705[1] ;
  assign IF_fpu_fState_S3_first__99_BITS_12_TO_0_05_SLT_ETC___d725 =
	     fpu_fState_S3_first__99_BITS_12_TO_0_05_SLT_7116___d208 ?
	       fpu_fProd_S3$D_OUT != 106'd0 || fpu_fState_S3$D_OUT[82] :
	       fpu_fState_S3_first__99_BITS_86_TO_82_04_OR_0__ETC___d705[0] ;
  assign IF_fpu_fState_S3_first__99_BIT_151_00_THEN_fpu_ETC___d729 =
	     fpu_fState_S3$D_OUT[151] ?
	       fpu_fState_S3$D_OUT[86:82] :
	       { IF_NOT_fpu_fState_S3_first__99_BITS_12_TO_0_05_ETC___d707,
		 IF_NOT_fpu_fState_S3_first__99_BITS_12_TO_0_05_ETC___d710,
		 NOT_fpu_fState_S3_first__99_BITS_12_TO_0_05_SL_ETC___d727 } ;
  assign IF_fpu_fState_S4_first__51_BITS_128_TO_118_68__ETC___d772 =
	     (fpu_fState_S4$D_OUT[128:118] == 11'd0) ?
	       13'd7170 :
	       { {2{fpu_fState_S4D_OUT_BITS_128_TO_118_MINUS_1023__q7[10]}},
		 fpu_fState_S4D_OUT_BITS_128_TO_118_MINUS_1023__q7 } ;
  assign IF_fpu_fState_S4_first__51_BITS_64_TO_54_63_EQ_ETC___d767 =
	     (fpu_fState_S4$D_OUT[64:54] == 11'd0) ?
	       13'd7170 :
	       { {2{fpu_fState_S4D_OUT_BITS_64_TO_54_MINUS_1023__q6[10]}},
		 fpu_fState_S4D_OUT_BITS_64_TO_54_MINUS_1023__q6 } ;
  assign IF_fpu_fState_S7_first__55_BITS_126_TO_114_66__ETC___d1107 =
	     IF_fpu_fState_S7_first__55_BITS_126_TO_114_66__ETC___d872 -
	     12'd3074 ;
  assign IF_fpu_fState_S7_first__55_BITS_126_TO_114_66__ETC___d872 =
	     (value__h45138[10:0] == 11'd0) ?
	       12'd3074 :
	       { value5138_BITS_10_TO_0_MINUS_1023__q8[10],
		 value5138_BITS_10_TO_0_MINUS_1023__q8 } ;
  assign IF_fpu_fState_S8_first__164_BITS_65_TO_55_168__ETC___d1190 =
	     (fpu_fState_S8$D_OUT[65:55] == 11'd0 &&
	      sfd__h45862[53:52] == 2'b01) ?
	       11'd1 :
	       fpu_fState_S8$D_OUT[65:55] ;
  assign IF_fpu_fState_S8_first__164_BITS_65_TO_55_168__ETC___d1215 =
	     (fpu_fState_S8$D_OUT[65:55] == 11'd2047) ?
	       fpu_fState_S8$D_OUT[65:55] :
	       _theResult___fst_exp__h46444 ;
  assign IF_fpu_fState_S8_first__164_BIT_67_167_AND_IF__ETC___d1264 =
	     (fpu_fState_S8$D_OUT[67] &&
	      IF_fpu_fState_S8_first__164_BITS_65_TO_55_168__ETC___d1215 ==
	      11'd0 &&
	      ((fpu_fState_S8$D_OUT[65:55] == 11'd2047) ?
		 fpu_fState_S8$D_OUT[54:3] :
		 _theResult___fst_sfd__h46445) ==
	      52'd0 &&
	      !fpu_fState_S8_first__164_BITS_75_TO_71_239_OR__ETC___d1247[0] &&
	      fpu_fState_S8$D_OUT[0]) ?
	       fpu_fState_S8$D_OUT[70:68] == 3'd3 :
	       ((fpu_fState_S8$D_OUT[65:55] == 11'd2047) ?
		  fpu_fState_S8$D_OUT[66] :
		  CASE_fpu_fState_S8D_OUT_BITS_70_TO_68_0_CASE__ETC__q14) ;
  assign IF_fpu_fState_S8_first__164_BIT_67_167_AND_IF__ETC___d1285 =
	     { IF_fpu_fState_S8_first__164_BIT_67_167_AND_IF__ETC___d1264,
	       (fpu_fState_S8$D_OUT[65:55] == 11'd2047) ?
		 fpu_fState_S8$D_OUT[65:3] :
		 CASE_fpu_fState_S8D_OUT_BITS_70_TO_68_0_CASE__ETC__q19,
	       fpu_fState_S8_first__164_BITS_75_TO_71_239_OR__ETC___d1247 } ;
  assign IF_sfdin4761_BIT_53_THEN_2_ELSE_0__q5 =
	     sfdin__h34761[53] ? 2'd2 : 2'd0 ;
  assign IF_sfdin5200_BIT_4_THEN_2_ELSE_0__q10 =
	     sfdin__h45200[4] ? 2'd2 : 2'd0 ;
  assign NOT_IF_fpu_fOperand_S0_first_BIT_195_THEN_IF_f_ETC___d150 =
	     (x__h321 != 11'd2047 || !_theResult___fst_sfd__h394[51]) &&
	     (fpu_fOperand_S0$D_OUT[129:119] != 11'd2047 ||
	      !fpu_fOperand_S0$D_OUT[118]) &&
	     (fpu_fOperand_S0$D_OUT[65:55] != 11'd2047 ||
	      !fpu_fOperand_S0$D_OUT[54]) &&
	     (fpu_fOperand_S0_first_BITS_129_TO_119_9_EQ_204_ETC___d130 ||
	      IF_fpu_fOperand_S0_first_BIT_195_THEN_IF_fpu_f_ETC___d131 &&
	      !fpu_fOperand_S0_first_BIT_195_AND_fpu_fOperand_ETC___d58) ;
  assign NOT_fpu_fOperand_S0_first_BITS_129_TO_119_9_EQ_ETC___d127 =
	     (fpu_fOperand_S0$D_OUT[129:119] != 11'd2047 ||
	      fpu_fOperand_S0$D_OUT[118:67] != 52'd0 ||
	      fpu_fOperand_S0$D_OUT[65:55] != 11'd0 ||
	      fpu_fOperand_S0$D_OUT[54:3] != 52'd0) &&
	     (fpu_fOperand_S0$D_OUT[129:119] != 11'd0 ||
	      fpu_fOperand_S0$D_OUT[118:67] != 52'd0 ||
	      fpu_fOperand_S0$D_OUT[65:55] != 11'd2047 ||
	      fpu_fOperand_S0$D_OUT[54:3] != 52'd0) &&
	     (x__h321 != 11'd2047 || _theResult___fst_sfd__h394 != 52'd0 ||
	      (fpu_fOperand_S0$D_OUT[129:119] != 11'd2047 ||
	       fpu_fOperand_S0$D_OUT[118:67] != 52'd0) &&
	      (fpu_fOperand_S0$D_OUT[65:55] != 11'd2047 ||
	       fpu_fOperand_S0$D_OUT[54:3] != 52'd0) ||
	      fpu_fOperand_S0_first_BIT_195_AND_fpu_fOperand_ETC___d58) &&
	     IF_IF_fpu_fOperand_S0_first_BIT_195_THEN_IF_fp_ETC___d126 ;
  assign NOT_fpu_fOperand_S0_first_BIT_130_4_EQ_fpu_fOp_ETC___d57 =
	     fpu_fOperand_S0$D_OUT[130] != fpu_fOperand_S0$D_OUT[66] ;
  assign NOT_fpu_fState_S3_first__99_BITS_12_TO_0_05_SL_ETC___d714 =
	     !fpu_fState_S3_first__99_BITS_12_TO_0_05_SLE_1023___d206 ||
	     (fpu_fState_S3_first__99_BITS_12_TO_0_05_SLT_7116___d208 ?
		fpu_fState_S3$D_OUT[84] :
		fpu_fState_S3_first__99_BITS_86_TO_82_04_OR_0__ETC___d705[2]) ;
  assign NOT_fpu_fState_S3_first__99_BITS_12_TO_0_05_SL_ETC___d727 =
	     { NOT_fpu_fState_S3_first__99_BITS_12_TO_0_05_SL_ETC___d714,
	       fpu_fState_S3_first__99_BITS_12_TO_0_05_SLE_1023___d206 ?
		 IF_fpu_fState_S3_first__99_BITS_12_TO_0_05_SLT_ETC___d720 :
		 fpu_fState_S3$D_OUT[83],
	       !fpu_fState_S3_first__99_BITS_12_TO_0_05_SLE_1023___d206 ||
	       IF_fpu_fState_S3_first__99_BITS_12_TO_0_05_SLT_ETC___d725 } ;
  assign NOT_fpu_fState_S4_first__51_BIT_130_57_62_OR_N_ETC___d788 =
	     !fpu_fState_S4$D_OUT[130] ||
	     (IF_fpu_fState_S4_first__51_BITS_64_TO_54_63_EQ_ETC___d767 ^
	      13'h1000) >
	     (IF_fpu_fState_S4_first__51_BITS_128_TO_118_68__ETC___d772 ^
	      13'h1000) ||
	     IF_fpu_fState_S4_first__51_BITS_64_TO_54_63_EQ_ETC___d767 ==
	     IF_fpu_fState_S4_first__51_BITS_128_TO_118_68__ETC___d772 &&
	     sfdBC__h35383 > sfdA__h35382 ;
  assign _0_CONCAT_IF_IF_7170_MINUS_fpu_fState_S3_first__ETC___d667 =
	     ({ 5'd0,
		IF_IF_7170_MINUS_fpu_fState_S3_first__99_BITS__ETC___d664 } ^
	      12'h800) <=
	     (IF_IF_7170_MINUS_fpu_fState_S3_first__99_BITS__ETC___d666 ^
	      12'h800) ;
  assign _0_CONCAT_IF_IF_fpu_fState_S7_first__55_BIT_128_ETC___d1108 =
	     ({ 6'd0,
		IF_IF_fpu_fState_S7_first__55_BIT_128_61_THEN__ETC___d1105 } ^
	      12'h800) <=
	     (IF_fpu_fState_S7_first__55_BITS_126_TO_114_66__ETC___d1107 ^
	      12'h800) ;
  assign _7170_MINUS_fpu_fState_S3_first__99_BITS_12_TO__ETC___d211 =
	     13'd7170 - fpu_fState_S3$D_OUT[12:0] ;
  assign _7170_MINUS_fpu_fState_S3_first__99_BITS_12_TO__ETC___d212 =
	     (_7170_MINUS_fpu_fState_S3_first__99_BITS_12_TO__ETC___d211 ^
	      13'h1000) <=
	     13'd4096 ;
  assign _theResult___exp__h46366 =
	     sfd__h45862[53] ?
	       ((fpu_fState_S8$D_OUT[65:55] == 11'd2046) ?
		  11'd2047 :
		  din_inc___2_exp__h46451) :
	       IF_fpu_fState_S8_first__164_BITS_65_TO_55_168__ETC___d1190 ;
  assign _theResult___fst__h20644 =
	     { fpu_fProd_S3_first__13_SRL_IF_7170_MINUS_fpu_f_ETC___d216[105:1],
	       fpu_fProd_S3_first__13_SRL_IF_7170_MINUS_fpu_f_ETC___d216[0] |
	       sfdlsb__h20642 } ;
  assign _theResult___fst_exp__h34767 =
	     sfdBC__h19463[105] ?
	       _theResult___fst_exp__h34789 :
	       _theResult___fst_exp__h34852 ;
  assign _theResult___fst_exp__h34770 =
	     (sfdBC__h19463[105] &&
	      IF_IF_7170_MINUS_fpu_fState_S3_first__99_BITS__ETC___d235 ==
	      12'd1023) ?
	       11'd2046 :
	       _theResult___fst_exp__h34767 ;
  assign _theResult___fst_exp__h34789 =
	     (din_exp__h34684 == 11'd0) ? 11'd2 : din_exp__h34684 + 11'd1 ;
  assign _theResult___fst_exp__h34804 =
	     (din_exp__h34684 == 11'd0) ? 11'd1 : din_exp__h34684 ;
  assign _theResult___fst_exp__h34843 =
	     din_exp__h34684 -
	     { 4'd0,
	       IF_IF_7170_MINUS_fpu_fState_S3_first__99_BITS__ETC___d664 } ;
  assign _theResult___fst_exp__h34849 =
	     (!sfdBC__h19463[105] && !sfdBC__h19463[104] &&
	      !sfdBC__h19463[103] &&
	      !sfdBC__h19463[102] &&
	      !sfdBC__h19463[101] &&
	      !sfdBC__h19463[100] &&
	      !sfdBC__h19463[99] &&
	      !sfdBC__h19463[98] &&
	      !sfdBC__h19463[97] &&
	      !sfdBC__h19463[96] &&
	      !sfdBC__h19463[95] &&
	      !sfdBC__h19463[94] &&
	      !sfdBC__h19463[93] &&
	      !sfdBC__h19463[92] &&
	      !sfdBC__h19463[91] &&
	      !sfdBC__h19463[90] &&
	      !sfdBC__h19463[89] &&
	      !sfdBC__h19463[88] &&
	      !sfdBC__h19463[87] &&
	      !sfdBC__h19463[86] &&
	      !sfdBC__h19463[85] &&
	      !sfdBC__h19463[84] &&
	      !sfdBC__h19463[83] &&
	      !sfdBC__h19463[82] &&
	      !sfdBC__h19463[81] &&
	      !sfdBC__h19463[80] &&
	      !sfdBC__h19463[79] &&
	      !sfdBC__h19463[78] &&
	      !sfdBC__h19463[77] &&
	      !sfdBC__h19463[76] &&
	      !sfdBC__h19463[75] &&
	      !sfdBC__h19463[74] &&
	      !sfdBC__h19463[73] &&
	      !sfdBC__h19463[72] &&
	      !sfdBC__h19463[71] &&
	      !sfdBC__h19463[70] &&
	      !sfdBC__h19463[69] &&
	      !sfdBC__h19463[68] &&
	      !sfdBC__h19463[67] &&
	      !sfdBC__h19463[66] &&
	      !sfdBC__h19463[65] &&
	      !sfdBC__h19463[64] &&
	      !sfdBC__h19463[63] &&
	      !sfdBC__h19463[62] &&
	      !sfdBC__h19463[61] &&
	      !sfdBC__h19463[60] &&
	      !sfdBC__h19463[59] &&
	      !sfdBC__h19463[58] &&
	      !sfdBC__h19463[57] &&
	      !sfdBC__h19463[56] &&
	      !sfdBC__h19463[55] &&
	      !sfdBC__h19463[54] &&
	      !sfdBC__h19463[53] &&
	      !sfdBC__h19463[52] &&
	      !sfdBC__h19463[51] &&
	      !sfdBC__h19463[50] &&
	      !sfdBC__h19463[49] &&
	      !sfdBC__h19463[48] &&
	      !sfdBC__h19463[47] &&
	      !sfdBC__h19463[46] &&
	      !sfdBC__h19463[45] &&
	      !sfdBC__h19463[44] &&
	      !sfdBC__h19463[43] &&
	      !sfdBC__h19463[42] &&
	      !sfdBC__h19463[41] &&
	      !sfdBC__h19463[40] &&
	      !sfdBC__h19463[39] &&
	      !sfdBC__h19463[38] &&
	      !sfdBC__h19463[37] &&
	      !sfdBC__h19463[36] &&
	      !sfdBC__h19463[35] &&
	      !sfdBC__h19463[34] &&
	      !sfdBC__h19463[33] &&
	      !sfdBC__h19463[32] &&
	      !sfdBC__h19463[31] &&
	      !sfdBC__h19463[30] &&
	      !sfdBC__h19463[29] &&
	      !sfdBC__h19463[28] &&
	      !sfdBC__h19463[27] &&
	      !sfdBC__h19463[26] &&
	      !sfdBC__h19463[25] &&
	      !sfdBC__h19463[24] &&
	      !sfdBC__h19463[23] &&
	      !sfdBC__h19463[22] &&
	      !sfdBC__h19463[21] &&
	      !sfdBC__h19463[20] &&
	      !sfdBC__h19463[19] &&
	      !sfdBC__h19463[18] &&
	      !sfdBC__h19463[17] &&
	      !sfdBC__h19463[16] &&
	      !sfdBC__h19463[15] &&
	      !sfdBC__h19463[14] &&
	      !sfdBC__h19463[13] &&
	      !sfdBC__h19463[12] &&
	      !sfdBC__h19463[11] &&
	      !sfdBC__h19463[10] &&
	      !sfdBC__h19463[9] &&
	      !sfdBC__h19463[8] &&
	      !sfdBC__h19463[7] &&
	      !sfdBC__h19463[6] &&
	      !sfdBC__h19463[5] &&
	      !sfdBC__h19463[4] &&
	      !sfdBC__h19463[3] &&
	      !sfdBC__h19463[2] &&
	      !sfdBC__h19463[1] &&
	      !sfdBC__h19463[0] ||
	      !_0_CONCAT_IF_IF_7170_MINUS_fpu_fState_S3_first__ETC___d667) ?
	       11'd0 :
	       _theResult___fst_exp__h34843 ;
  assign _theResult___fst_exp__h34852 =
	     (!sfdBC__h19463[105] && sfdBC__h19463[104]) ?
	       _theResult___fst_exp__h34804 :
	       _theResult___fst_exp__h34849 ;
  assign _theResult___fst_exp__h45206 =
	     sfd__h36933[56] ?
	       _theResult___fst_exp__h45228 :
	       _theResult___fst_exp__h45291 ;
  assign _theResult___fst_exp__h45209 =
	     (sfd__h36933[56] &&
	      IF_fpu_fState_S7_first__55_BITS_126_TO_114_66__ETC___d872 ==
	      12'd1023) ?
	       11'd2046 :
	       _theResult___fst_exp__h45206 ;
  assign _theResult___fst_exp__h45228 =
	     (value__h45138[10:0] == 11'd0) ?
	       11'd2 :
	       value__h45138[10:0] + 11'd1 ;
  assign _theResult___fst_exp__h45243 =
	     (value__h45138[10:0] == 11'd0) ? 11'd1 : value__h45138[10:0] ;
  assign _theResult___fst_exp__h45282 =
	     value__h45138[10:0] -
	     { 5'd0,
	       IF_IF_fpu_fState_S7_first__55_BIT_128_61_THEN__ETC___d1105 } ;
  assign _theResult___fst_exp__h45288 =
	     (!sfd__h36933[56] && !sfd__h36933[55] && !sfd__h36933[54] &&
	      !sfd__h36933[53] &&
	      !sfd__h36933[52] &&
	      !sfd__h36933[51] &&
	      !sfd__h36933[50] &&
	      !sfd__h36933[49] &&
	      !sfd__h36933[48] &&
	      !sfd__h36933[47] &&
	      !sfd__h36933[46] &&
	      !sfd__h36933[45] &&
	      !sfd__h36933[44] &&
	      !sfd__h36933[43] &&
	      !sfd__h36933[42] &&
	      !sfd__h36933[41] &&
	      !sfd__h36933[40] &&
	      !sfd__h36933[39] &&
	      !sfd__h36933[38] &&
	      !sfd__h36933[37] &&
	      !sfd__h36933[36] &&
	      !sfd__h36933[35] &&
	      !sfd__h36933[34] &&
	      !sfd__h36933[33] &&
	      !sfd__h36933[32] &&
	      !sfd__h36933[31] &&
	      !sfd__h36933[30] &&
	      !sfd__h36933[29] &&
	      !sfd__h36933[28] &&
	      !sfd__h36933[27] &&
	      !sfd__h36933[26] &&
	      !sfd__h36933[25] &&
	      !sfd__h36933[24] &&
	      !sfd__h36933[23] &&
	      !sfd__h36933[22] &&
	      !sfd__h36933[21] &&
	      !sfd__h36933[20] &&
	      !sfd__h36933[19] &&
	      !sfd__h36933[18] &&
	      !sfd__h36933[17] &&
	      !sfd__h36933[16] &&
	      !sfd__h36933[15] &&
	      !sfd__h36933[14] &&
	      !sfd__h36933[13] &&
	      !sfd__h36933[12] &&
	      !sfd__h36933[11] &&
	      !sfd__h36933[10] &&
	      !sfd__h36933[9] &&
	      !sfd__h36933[8] &&
	      !sfd__h36933[7] &&
	      !sfd__h36933[6] &&
	      !sfd__h36933[5] &&
	      !sfd__h36933[4] &&
	      !sfd__h36933[3] &&
	      !sfd__h36933[2] &&
	      !sfd__h36933[1] &&
	      !sfd__h36933[0] ||
	      !_0_CONCAT_IF_IF_fpu_fState_S7_first__55_BIT_128_ETC___d1108) ?
	       11'd0 :
	       _theResult___fst_exp__h45282 ;
  assign _theResult___fst_exp__h45291 =
	     (!sfd__h36933[56] && sfd__h36933[55]) ?
	       _theResult___fst_exp__h45243 :
	       _theResult___fst_exp__h45288 ;
  assign _theResult___fst_sfd__h394 =
	     fpu_fOperand_S0$D_OUT[195] ?
	       fpu_fOperand_S0$D_OUT[182:131] :
	       52'd0 ;
  assign _theResult___sfd__h46367 =
	     sfd__h45862[53] ?
	       ((fpu_fState_S8$D_OUT[65:55] == 11'd2046) ?
		  52'd0 :
		  sfd__h45862[52:1]) :
	       sfd__h45862[51:0] ;
  assign _theResult___snd__h34784 = { sfdBC__h19463[104:0], 1'd0 } ;
  assign _theResult___snd__h34798 =
	     (!sfdBC__h19463[105] && sfdBC__h19463[104]) ?
	       _theResult___snd__h34800 :
	       _theResult___snd__h34812 ;
  assign _theResult___snd__h34800 = { sfdBC__h19463[103:0], 2'd0 } ;
  assign _theResult___snd__h34812 =
	     (!sfdBC__h19463[105] && !sfdBC__h19463[104] &&
	      !sfdBC__h19463[103] &&
	      !sfdBC__h19463[102] &&
	      !sfdBC__h19463[101] &&
	      !sfdBC__h19463[100] &&
	      !sfdBC__h19463[99] &&
	      !sfdBC__h19463[98] &&
	      !sfdBC__h19463[97] &&
	      !sfdBC__h19463[96] &&
	      !sfdBC__h19463[95] &&
	      !sfdBC__h19463[94] &&
	      !sfdBC__h19463[93] &&
	      !sfdBC__h19463[92] &&
	      !sfdBC__h19463[91] &&
	      !sfdBC__h19463[90] &&
	      !sfdBC__h19463[89] &&
	      !sfdBC__h19463[88] &&
	      !sfdBC__h19463[87] &&
	      !sfdBC__h19463[86] &&
	      !sfdBC__h19463[85] &&
	      !sfdBC__h19463[84] &&
	      !sfdBC__h19463[83] &&
	      !sfdBC__h19463[82] &&
	      !sfdBC__h19463[81] &&
	      !sfdBC__h19463[80] &&
	      !sfdBC__h19463[79] &&
	      !sfdBC__h19463[78] &&
	      !sfdBC__h19463[77] &&
	      !sfdBC__h19463[76] &&
	      !sfdBC__h19463[75] &&
	      !sfdBC__h19463[74] &&
	      !sfdBC__h19463[73] &&
	      !sfdBC__h19463[72] &&
	      !sfdBC__h19463[71] &&
	      !sfdBC__h19463[70] &&
	      !sfdBC__h19463[69] &&
	      !sfdBC__h19463[68] &&
	      !sfdBC__h19463[67] &&
	      !sfdBC__h19463[66] &&
	      !sfdBC__h19463[65] &&
	      !sfdBC__h19463[64] &&
	      !sfdBC__h19463[63] &&
	      !sfdBC__h19463[62] &&
	      !sfdBC__h19463[61] &&
	      !sfdBC__h19463[60] &&
	      !sfdBC__h19463[59] &&
	      !sfdBC__h19463[58] &&
	      !sfdBC__h19463[57] &&
	      !sfdBC__h19463[56] &&
	      !sfdBC__h19463[55] &&
	      !sfdBC__h19463[54] &&
	      !sfdBC__h19463[53] &&
	      !sfdBC__h19463[52] &&
	      !sfdBC__h19463[51] &&
	      !sfdBC__h19463[50] &&
	      !sfdBC__h19463[49] &&
	      !sfdBC__h19463[48] &&
	      !sfdBC__h19463[47] &&
	      !sfdBC__h19463[46] &&
	      !sfdBC__h19463[45] &&
	      !sfdBC__h19463[44] &&
	      !sfdBC__h19463[43] &&
	      !sfdBC__h19463[42] &&
	      !sfdBC__h19463[41] &&
	      !sfdBC__h19463[40] &&
	      !sfdBC__h19463[39] &&
	      !sfdBC__h19463[38] &&
	      !sfdBC__h19463[37] &&
	      !sfdBC__h19463[36] &&
	      !sfdBC__h19463[35] &&
	      !sfdBC__h19463[34] &&
	      !sfdBC__h19463[33] &&
	      !sfdBC__h19463[32] &&
	      !sfdBC__h19463[31] &&
	      !sfdBC__h19463[30] &&
	      !sfdBC__h19463[29] &&
	      !sfdBC__h19463[28] &&
	      !sfdBC__h19463[27] &&
	      !sfdBC__h19463[26] &&
	      !sfdBC__h19463[25] &&
	      !sfdBC__h19463[24] &&
	      !sfdBC__h19463[23] &&
	      !sfdBC__h19463[22] &&
	      !sfdBC__h19463[21] &&
	      !sfdBC__h19463[20] &&
	      !sfdBC__h19463[19] &&
	      !sfdBC__h19463[18] &&
	      !sfdBC__h19463[17] &&
	      !sfdBC__h19463[16] &&
	      !sfdBC__h19463[15] &&
	      !sfdBC__h19463[14] &&
	      !sfdBC__h19463[13] &&
	      !sfdBC__h19463[12] &&
	      !sfdBC__h19463[11] &&
	      !sfdBC__h19463[10] &&
	      !sfdBC__h19463[9] &&
	      !sfdBC__h19463[8] &&
	      !sfdBC__h19463[7] &&
	      !sfdBC__h19463[6] &&
	      !sfdBC__h19463[5] &&
	      !sfdBC__h19463[4] &&
	      !sfdBC__h19463[3] &&
	      !sfdBC__h19463[2] &&
	      !sfdBC__h19463[1] &&
	      !sfdBC__h19463[0]) ?
	       sfdBC__h19463 :
	       _theResult___snd__h34818 ;
  assign _theResult___snd__h34818 =
	     { IF_0_CONCAT_IF_IF_7170_MINUS_fpu_fState_S3_fir_ETC__q4[103:0],
	       2'd0 } ;
  assign _theResult___snd__h34836 =
	     sfdBC__h19463 <<
	     IF_IF_7170_MINUS_fpu_fState_S3_first__99_BITS__ETC___d666 ;
  assign _theResult___snd__h34841 =
	     sfdBC__h19463 <<
	     IF_IF_7170_MINUS_fpu_fState_S3_first__99_BITS__ETC___d664 ;
  assign _theResult___snd__h45223 = { sfd__h36933[55:0], 1'd0 } ;
  assign _theResult___snd__h45237 =
	     (!sfd__h36933[56] && sfd__h36933[55]) ?
	       _theResult___snd__h45239 :
	       _theResult___snd__h45251 ;
  assign _theResult___snd__h45239 = { sfd__h36933[54:0], 2'd0 } ;
  assign _theResult___snd__h45251 =
	     (!sfd__h36933[56] && !sfd__h36933[55] && !sfd__h36933[54] &&
	      !sfd__h36933[53] &&
	      !sfd__h36933[52] &&
	      !sfd__h36933[51] &&
	      !sfd__h36933[50] &&
	      !sfd__h36933[49] &&
	      !sfd__h36933[48] &&
	      !sfd__h36933[47] &&
	      !sfd__h36933[46] &&
	      !sfd__h36933[45] &&
	      !sfd__h36933[44] &&
	      !sfd__h36933[43] &&
	      !sfd__h36933[42] &&
	      !sfd__h36933[41] &&
	      !sfd__h36933[40] &&
	      !sfd__h36933[39] &&
	      !sfd__h36933[38] &&
	      !sfd__h36933[37] &&
	      !sfd__h36933[36] &&
	      !sfd__h36933[35] &&
	      !sfd__h36933[34] &&
	      !sfd__h36933[33] &&
	      !sfd__h36933[32] &&
	      !sfd__h36933[31] &&
	      !sfd__h36933[30] &&
	      !sfd__h36933[29] &&
	      !sfd__h36933[28] &&
	      !sfd__h36933[27] &&
	      !sfd__h36933[26] &&
	      !sfd__h36933[25] &&
	      !sfd__h36933[24] &&
	      !sfd__h36933[23] &&
	      !sfd__h36933[22] &&
	      !sfd__h36933[21] &&
	      !sfd__h36933[20] &&
	      !sfd__h36933[19] &&
	      !sfd__h36933[18] &&
	      !sfd__h36933[17] &&
	      !sfd__h36933[16] &&
	      !sfd__h36933[15] &&
	      !sfd__h36933[14] &&
	      !sfd__h36933[13] &&
	      !sfd__h36933[12] &&
	      !sfd__h36933[11] &&
	      !sfd__h36933[10] &&
	      !sfd__h36933[9] &&
	      !sfd__h36933[8] &&
	      !sfd__h36933[7] &&
	      !sfd__h36933[6] &&
	      !sfd__h36933[5] &&
	      !sfd__h36933[4] &&
	      !sfd__h36933[3] &&
	      !sfd__h36933[2] &&
	      !sfd__h36933[1] &&
	      !sfd__h36933[0]) ?
	       sfd__h36933 :
	       _theResult___snd__h45257 ;
  assign _theResult___snd__h45257 =
	     { IF_0_CONCAT_IF_IF_fpu_fState_S7_first__55_BIT__ETC__q9[54:0],
	       2'd0 } ;
  assign _theResult___snd__h45275 =
	     sfd__h36933 <<
	     IF_fpu_fState_S7_first__55_BITS_126_TO_114_66__ETC___d1107 ;
  assign _theResult___snd__h45280 =
	     sfd__h36933 <<
	     IF_IF_fpu_fState_S7_first__55_BIT_128_61_THEN__ETC___d1105 ;
  assign _theResult___snd_fst__h34869 =
	     { IF_sfdin4761_BIT_53_THEN_2_ELSE_0__q5[1],
	       { sfdin__h34761[52:0], 52'd0 } != 105'd0 } ;
  assign _theResult___snd_fst__h45308 =
	     { IF_sfdin5200_BIT_4_THEN_2_ELSE_0__q10[1],
	       { sfdin__h45200[3:0], 52'd0 } != 56'd0 } ;
  assign _theResult___snd_snd__h35189 =
	     (fpu_fProd_S3$D_OUT == 106'd0) ? 2'd0 : 2'd1 ;
  assign _theResult___snd_snd_snd__h35187 =
	     fpu_fState_S3_first__99_BITS_12_TO_0_05_SLT_7116___d208 ?
	       _theResult___snd_snd__h35189 :
	       guardBC__h19467 ;
  assign din_exp4684_MINUS_1023__q3 = din_exp__h34684 - 11'd1023 ;
  assign din_exp__h34684 =
	     _7170_MINUS_fpu_fState_S3_first__99_BITS_12_TO__ETC___d212 ?
	       value__h34701[10:0] :
	       11'd0 ;
  assign din_inc___2_exp__h46451 = fpu_fState_S8$D_OUT[65:55] + 11'd1 ;
  assign fpu_fOperand_S0D_OUT_BITS_129_TO_119_MINUS_1023__q15 =
	     fpu_fOperand_S0$D_OUT[129:119] - 11'd1023 ;
  assign fpu_fOperand_S0D_OUT_BITS_65_TO_55_MINUS_1023__q16 =
	     fpu_fOperand_S0$D_OUT[65:55] - 11'd1023 ;
  assign fpu_fOperand_S0_first_BITS_129_TO_119_9_EQ_204_ETC___d130 =
	     fpu_fOperand_S0$D_OUT[129:119] == 11'd2047 &&
	     fpu_fOperand_S0$D_OUT[118:67] == 52'd0 &&
	     fpu_fOperand_S0$D_OUT[65:55] == 11'd0 &&
	     fpu_fOperand_S0$D_OUT[54:3] == 52'd0 ||
	     fpu_fOperand_S0$D_OUT[129:119] == 11'd0 &&
	     fpu_fOperand_S0$D_OUT[118:67] == 52'd0 &&
	     fpu_fOperand_S0$D_OUT[65:55] == 11'd2047 &&
	     fpu_fOperand_S0$D_OUT[54:3] == 52'd0 ;
  assign fpu_fOperand_S0_first_BITS_129_TO_119_9_EQ_204_ETC___d60 =
	     fpu_fOperand_S0$D_OUT[129:119] == 11'd2047 &&
	     fpu_fOperand_S0$D_OUT[118:67] == 52'd0 ||
	     fpu_fOperand_S0$D_OUT[65:55] == 11'd2047 &&
	     fpu_fOperand_S0$D_OUT[54:3] == 52'd0 ||
	     x__h321 == 11'd0 && _theResult___fst_sfd__h394 == 52'd0 &&
	     (fpu_fOperand_S0$D_OUT[129:119] == 11'd0 &&
	      fpu_fOperand_S0$D_OUT[118:67] == 52'd0 ||
	      fpu_fOperand_S0$D_OUT[65:55] == 11'd0 &&
	      fpu_fOperand_S0$D_OUT[54:3] == 52'd0) &&
	     fpu_fOperand_S0_first_BIT_195_AND_fpu_fOperand_ETC___d58 ;
  assign fpu_fOperand_S0_first_BIT_195_AND_fpu_fOperand_ETC___d58 =
	     (fpu_fOperand_S0$D_OUT[195] && fpu_fOperand_S0$D_OUT[194]) ==
	     NOT_fpu_fOperand_S0_first_BIT_130_4_EQ_fpu_fOp_ETC___d57 ;
  assign fpu_fProd_S3_first__13_SRL_IF_7170_MINUS_fpu_f_ETC___d216 =
	     fpu_fProd_S3$D_OUT >>
	     _7170_MINUS_fpu_fState_S3_first__99_BITS_12_TO__ETC___d211 ;
  assign fpu_fState_S3_first__99_BITS_12_TO_0_05_SLE_1023___d206 =
	     (fpu_fState_S3$D_OUT[12:0] ^ 13'h1000) <= 13'd5119 ;
  assign fpu_fState_S3_first__99_BITS_12_TO_0_05_SLT_7116___d208 =
	     (fpu_fState_S3$D_OUT[12:0] ^ 13'h1000) < 13'd3020 ;
  assign fpu_fState_S3_first__99_BITS_86_TO_82_04_OR_0__ETC___d705 =
	     fpu_fState_S3$D_OUT[86:82] |
	     { 2'd0,
	       sfdBC__h19463[105] &&
	       IF_IF_7170_MINUS_fpu_fState_S3_first__99_BITS__ETC___d235 ==
	       12'd1023,
	       _theResult___fst_exp__h34770 == 11'd0 &&
	       guardBC__h19467 != 2'd0,
	       sfdBC__h19463[105] &&
	       IF_IF_7170_MINUS_fpu_fState_S3_first__99_BITS__ETC___d235 ==
	       12'd1023 } ;
  assign fpu_fState_S4D_OUT_BITS_128_TO_118_MINUS_1023__q7 =
	     fpu_fState_S4$D_OUT[128:118] - 11'd1023 ;
  assign fpu_fState_S4D_OUT_BITS_64_TO_54_MINUS_1023__q6 =
	     fpu_fState_S4$D_OUT[64:54] - 11'd1023 ;
  assign fpu_fState_S5_first__05_BITS_56_TO_0_14_SRL_IF_ETC___d819 =
	     fpu_fState_S5$D_OUT[56:0] >> fpu_fState_S5$D_OUT[126:114] ;
  assign fpu_fState_S7_first__55_BITS_137_TO_133_60_OR__ETC___d1146 =
	     fpu_fState_S7$D_OUT[137:133] |
	     { 2'd0,
	       sfd__h36933[56] &&
	       IF_fpu_fState_S7_first__55_BITS_126_TO_114_66__ETC___d872 ==
	       12'd1023,
	       _theResult___fst_exp__h45209 == 11'd0 && guard__h36937 != 2'd0,
	       sfd__h36933[56] &&
	       IF_fpu_fState_S7_first__55_BITS_126_TO_114_66__ETC___d872 ==
	       12'd1023 } ;
  assign fpu_fState_S8_first__164_BITS_75_TO_71_239_OR__ETC___d1247 =
	     fpu_fState_S8$D_OUT[75:71] |
	     { 2'd0,
	       IF_fpu_fState_S8_first__164_BITS_65_TO_55_168__ETC___d1215 ==
	       11'd2047 &&
	       ((fpu_fState_S8$D_OUT[65:55] == 11'd2047) ?
		  fpu_fState_S8$D_OUT[54:3] :
		  _theResult___fst_sfd__h46445) ==
	       52'd0,
	       1'd0,
	       fpu_fState_S8$D_OUT[65:55] != 11'd2047 &&
	       fpu_fState_S8$D_OUT[2:1] != 2'b0 } ;
  assign guardBC__h19467 =
	     (sfdBC__h19463[105] &&
	      IF_IF_7170_MINUS_fpu_fState_S3_first__99_BITS__ETC___d235 ==
	      12'd1023) ?
	       2'd3 :
	       _theResult___snd_fst__h34869 ;
  assign guard__h36191 = fpu_fState_S5$D_OUT[56:0] << x__h36295 ;
  assign guard__h36937 =
	     (sfd__h36933[56] &&
	      IF_fpu_fState_S7_first__55_BITS_126_TO_114_66__ETC___d872 ==
	      12'd1023) ?
	       2'd3 :
	       _theResult___snd_fst__h45308 ;
  assign out_exp__h46369 =
	     fpu_fState_S8$D_OUT[3] ?
	       _theResult___exp__h46366 :
	       fpu_fState_S8$D_OUT[65:55] ;
  assign out_sfd__h46370 =
	     fpu_fState_S8$D_OUT[3] ?
	       _theResult___sfd__h46367 :
	       fpu_fState_S8$D_OUT[54:3] ;
  assign result__h36196 =
	     { fpu_fState_S5_first__05_BITS_56_TO_0_14_SRL_IF_ETC___d819[56:1],
	       fpu_fState_S5_first__05_BITS_56_TO_0_14_SRL_IF_ETC___d819[0] |
	       guard__h36191 != 57'd0 } ;
  assign sfdA__h35382 =
	     { 1'b0,
	       fpu_fState_S4$D_OUT[128:118] != 11'd0,
	       fpu_fState_S4$D_OUT[117:66],
	       3'b0 } ;
  assign sfdBC__h19463 =
	     _7170_MINUS_fpu_fState_S3_first__99_BITS_12_TO__ETC___d212 ?
	       fpu_fProd_S3$D_OUT :
	       _theResult___fst__h20644 ;
  assign sfdBC__h35383 =
	     { 1'b0,
	       fpu_fState_S4$D_OUT[64:54] != 11'd0,
	       fpu_fState_S4$D_OUT[53:0],
	       1'b0 } ;
  assign sfd__h3217 = { 1'd1, _theResult___fst_sfd__h394[50:0] } ;
  assign sfd__h3220 = { 1'd1, fpu_fOperand_S0$D_OUT[117:67] } ;
  assign sfd__h3223 = { 1'd1, fpu_fOperand_S0$D_OUT[53:3] } ;
  assign sfd__h36933 =
	     fpu_fState_S7$D_OUT[128] ?
	       fpu_fState_S7$D_OUT[56:0] :
	       fpu_fState_S7$D_OUT[113:57] ;
  assign sfd__h45862 =
	     { 1'b0,
	       fpu_fState_S8$D_OUT[65:55] != 11'd0,
	       fpu_fState_S8$D_OUT[54:3] } +
	     54'd1 ;
  assign sfdin__h34761 =
	     sfdBC__h19463[105] ?
	       _theResult___snd__h34784 :
	       _theResult___snd__h34798 ;
  assign sfdin__h45200 =
	     sfd__h36933[56] ?
	       _theResult___snd__h45223 :
	       _theResult___snd__h45237 ;
  assign sfdlsb__h20642 = x__h20713 != 106'd0 ;
  assign value5138_BITS_10_TO_0_MINUS_1023__q8 =
	     value__h45138[10:0] - 11'd1023 ;
  assign value__h34701 = fpu_fState_S3$D_OUT[12:0] + 13'd1023 ;
  assign value__h45138 = fpu_fState_S7$D_OUT[126:114] + 13'd1023 ;
  assign x__h18075 =
	     { fpu_fOperand_S0$D_OUT[129:119] != 11'd0,
	       fpu_fOperand_S0$D_OUT[118:67] } ;
  assign x__h18087 =
	     { fpu_fOperand_S0$D_OUT[65:55] != 11'd0,
	       fpu_fOperand_S0$D_OUT[54:3] } ;
  assign x__h20713 = fpu_fProd_S3$D_OUT << x__h20746 ;
  assign x__h20746 =
	     13'd106 -
	     _7170_MINUS_fpu_fState_S3_first__99_BITS_12_TO__ETC___d211 ;
  assign x__h321 =
	     fpu_fOperand_S0$D_OUT[195] ?
	       fpu_fOperand_S0$D_OUT[193:183] :
	       11'd0 ;
  assign x__h35224 =
	     fpu_fState_S3_first__99_BITS_12_TO_0_05_SLE_1023___d206 ?
	       _theResult___snd_snd_snd__h35187 :
	       2'd3 ;
  assign x__h35761 =
	     { 1'b0,
	       NOT_fpu_fState_S4_first__51_BIT_130_57_62_OR_N_ETC___d788 ?
		 { fpu_fState_S4$D_OUT[64:54] != 11'd0,
		   fpu_fState_S4$D_OUT[53:0],
		   1'b0 } :
		 { fpu_fState_S4$D_OUT[128:118] != 11'd0,
		   fpu_fState_S4$D_OUT[117:66],
		   3'b0 } } ;
  assign x__h35765 =
	     { 1'b0,
	       NOT_fpu_fState_S4_first__51_BIT_130_57_62_OR_N_ETC___d788 ?
		 { fpu_fState_S4$D_OUT[128:118] != 11'd0,
		   fpu_fState_S4$D_OUT[117:66],
		   3'b0 } :
		 { fpu_fState_S4$D_OUT[64:54] != 11'd0,
		   fpu_fState_S4$D_OUT[53:0],
		   1'b0 } } ;
  assign x__h36183 =
	     fpu_fState_S5$D_OUT[215] ?
	       fpu_fState_S5$D_OUT[56:0] :
	       (((fpu_fState_S5$D_OUT[126:114] ^ 13'h1000) < 13'd4153) ?
		  result__h36196 :
		  ((fpu_fState_S5$D_OUT[56:0] == 57'd0) ?
		     fpu_fState_S5$D_OUT[56:0] :
		     57'd1)) ;
  assign x__h36295 = 13'd57 - fpu_fState_S5$D_OUT[126:114] ;
  assign x__h36698 = fpu_fState_S6$D_OUT[113:57] + fpu_fState_S6$D_OUT[56:0] ;
  assign x__h36707 = fpu_fState_S6$D_OUT[113:57] - fpu_fState_S6$D_OUT[56:0] ;
  assign x__h45591 = fpu_fState_S7$D_OUT[202] ? 2'd0 : guard__h36937 ;
  always@(fpu_fState_S8$D_OUT or out_sfd__h46370 or _theResult___sfd__h46367)
  begin
    case (fpu_fState_S8$D_OUT[2:1])
      2'b0, 2'b01:
	  CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q1 =
	      fpu_fState_S8$D_OUT[54:3];
      2'b10:
	  CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q1 =
	      out_sfd__h46370;
      2'b11:
	  CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q1 =
	      _theResult___sfd__h46367;
    endcase
  end
  always@(fpu_fState_S8$D_OUT or _theResult___sfd__h46367)
  begin
    case (fpu_fState_S8$D_OUT[2:1])
      2'b0:
	  CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q2 =
	      fpu_fState_S8$D_OUT[54:3];
      2'b01, 2'b10, 2'b11:
	  CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q2 =
	      _theResult___sfd__h46367;
    endcase
  end
  always@(fpu_fState_S8$D_OUT or
	  CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q1 or
	  CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q2 or
	  _theResult___sfd__h46367)
  begin
    case (fpu_fState_S8$D_OUT[70:68])
      3'd0:
	  _theResult___fst_sfd__h46445 =
	      CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q1;
      3'd1:
	  _theResult___fst_sfd__h46445 =
	      CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q2;
      3'd2:
	  _theResult___fst_sfd__h46445 =
	      (fpu_fState_S8$D_OUT[2:1] == 2'b0 || fpu_fState_S8$D_OUT[66]) ?
		fpu_fState_S8$D_OUT[54:3] :
		_theResult___sfd__h46367;
      3'd3:
	  _theResult___fst_sfd__h46445 =
	      (fpu_fState_S8$D_OUT[2:1] == 2'b0) ?
		fpu_fState_S8$D_OUT[54:3] :
		(fpu_fState_S8$D_OUT[66] ?
		   _theResult___sfd__h46367 :
		   fpu_fState_S8$D_OUT[54:3]);
      3'd4: _theResult___fst_sfd__h46445 = fpu_fState_S8$D_OUT[54:3];
      default: _theResult___fst_sfd__h46445 = 52'd0;
    endcase
  end
  always@(fpu_fState_S8$D_OUT or out_exp__h46369 or _theResult___exp__h46366)
  begin
    case (fpu_fState_S8$D_OUT[2:1])
      2'b0, 2'b01:
	  CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q11 =
	      fpu_fState_S8$D_OUT[65:55];
      2'b10:
	  CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q11 =
	      out_exp__h46369;
      2'b11:
	  CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q11 =
	      _theResult___exp__h46366;
    endcase
  end
  always@(fpu_fState_S8$D_OUT or _theResult___exp__h46366)
  begin
    case (fpu_fState_S8$D_OUT[2:1])
      2'b0:
	  CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q12 =
	      fpu_fState_S8$D_OUT[65:55];
      2'b01, 2'b10, 2'b11:
	  CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q12 =
	      _theResult___exp__h46366;
    endcase
  end
  always@(fpu_fState_S8$D_OUT or
	  CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q11 or
	  CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q12 or
	  _theResult___exp__h46366)
  begin
    case (fpu_fState_S8$D_OUT[70:68])
      3'd0:
	  _theResult___fst_exp__h46444 =
	      CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q11;
      3'd1:
	  _theResult___fst_exp__h46444 =
	      CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q12;
      3'd2:
	  _theResult___fst_exp__h46444 =
	      (fpu_fState_S8$D_OUT[2:1] == 2'b0 || fpu_fState_S8$D_OUT[66]) ?
		fpu_fState_S8$D_OUT[65:55] :
		_theResult___exp__h46366;
      3'd3:
	  _theResult___fst_exp__h46444 =
	      (fpu_fState_S8$D_OUT[2:1] == 2'b0) ?
		fpu_fState_S8$D_OUT[65:55] :
		(fpu_fState_S8$D_OUT[66] ?
		   _theResult___exp__h46366 :
		   fpu_fState_S8$D_OUT[65:55]);
      3'd4: _theResult___fst_exp__h46444 = fpu_fState_S8$D_OUT[65:55];
      default: _theResult___fst_exp__h46444 = 11'd0;
    endcase
  end
  always@(fpu_fState_S8$D_OUT)
  begin
    case (fpu_fState_S8$D_OUT[2:1])
      2'b0, 2'b01, 2'b10:
	  CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q13 =
	      fpu_fState_S8$D_OUT[66];
      2'd3:
	  CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q13 =
	      fpu_fState_S8$D_OUT[2:1] == 2'b11 && fpu_fState_S8$D_OUT[66];
    endcase
  end
  always@(fpu_fState_S8$D_OUT or
	  CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q13)
  begin
    case (fpu_fState_S8$D_OUT[70:68])
      3'd0:
	  CASE_fpu_fState_S8D_OUT_BITS_70_TO_68_0_CASE__ETC__q14 =
	      CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q13;
      3'd1:
	  CASE_fpu_fState_S8D_OUT_BITS_70_TO_68_0_CASE__ETC__q14 =
	      (fpu_fState_S8$D_OUT[2:1] == 2'b0) ?
		fpu_fState_S8$D_OUT[66] :
		(fpu_fState_S8$D_OUT[2:1] == 2'b01 ||
		 fpu_fState_S8$D_OUT[2:1] == 2'b10 ||
		 fpu_fState_S8$D_OUT[2:1] == 2'b11) &&
		fpu_fState_S8$D_OUT[66];
      3'd2, 3'd3:
	  CASE_fpu_fState_S8D_OUT_BITS_70_TO_68_0_CASE__ETC__q14 =
	      fpu_fState_S8$D_OUT[66];
      default: CASE_fpu_fState_S8D_OUT_BITS_70_TO_68_0_CASE__ETC__q14 =
		   fpu_fState_S8$D_OUT[70:68] == 3'd4 &&
		   fpu_fState_S8$D_OUT[66];
    endcase
  end
  always@(fpu_fState_S8$D_OUT or
	  IF_0b0_CONCAT_NOT_fpu_fState_S8_first__164_BIT_ETC___d1269)
  begin
    case (fpu_fState_S8$D_OUT[2:1])
      2'b0, 2'b01:
	  CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q17 =
	      fpu_fState_S8$D_OUT[65:3];
      2'b10:
	  CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q17 =
	      fpu_fState_S8$D_OUT[3] ?
		IF_0b0_CONCAT_NOT_fpu_fState_S8_first__164_BIT_ETC___d1269 :
		fpu_fState_S8$D_OUT[65:3];
      2'b11:
	  CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q17 =
	      IF_0b0_CONCAT_NOT_fpu_fState_S8_first__164_BIT_ETC___d1269;
    endcase
  end
  always@(fpu_fState_S8$D_OUT or
	  IF_0b0_CONCAT_NOT_fpu_fState_S8_first__164_BIT_ETC___d1269)
  begin
    case (fpu_fState_S8$D_OUT[2:1])
      2'b0:
	  CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q18 =
	      fpu_fState_S8$D_OUT[65:3];
      2'b01, 2'b10, 2'b11:
	  CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q18 =
	      IF_0b0_CONCAT_NOT_fpu_fState_S8_first__164_BIT_ETC___d1269;
    endcase
  end
  always@(fpu_fState_S8$D_OUT or
	  CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q17 or
	  CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q18 or
	  IF_0b0_CONCAT_NOT_fpu_fState_S8_first__164_BIT_ETC___d1269)
  begin
    case (fpu_fState_S8$D_OUT[70:68])
      3'd0:
	  CASE_fpu_fState_S8D_OUT_BITS_70_TO_68_0_CASE__ETC__q19 =
	      CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q17;
      3'd1:
	  CASE_fpu_fState_S8D_OUT_BITS_70_TO_68_0_CASE__ETC__q19 =
	      CASE_fpu_fState_S8D_OUT_BITS_2_TO_1_0b0_fpu_f_ETC__q18;
      3'd2:
	  CASE_fpu_fState_S8D_OUT_BITS_70_TO_68_0_CASE__ETC__q19 =
	      (fpu_fState_S8$D_OUT[2:1] == 2'b0 || fpu_fState_S8$D_OUT[66]) ?
		fpu_fState_S8$D_OUT[65:3] :
		IF_0b0_CONCAT_NOT_fpu_fState_S8_first__164_BIT_ETC___d1269;
      3'd3:
	  CASE_fpu_fState_S8D_OUT_BITS_70_TO_68_0_CASE__ETC__q19 =
	      (fpu_fState_S8$D_OUT[2:1] == 2'b0) ?
		fpu_fState_S8$D_OUT[65:3] :
		(fpu_fState_S8$D_OUT[66] ?
		   IF_0b0_CONCAT_NOT_fpu_fState_S8_first__164_BIT_ETC___d1269 :
		   fpu_fState_S8$D_OUT[65:3]);
      3'd4:
	  CASE_fpu_fState_S8D_OUT_BITS_70_TO_68_0_CASE__ETC__q19 =
	      fpu_fState_S8$D_OUT[65:3];
      default: CASE_fpu_fState_S8D_OUT_BITS_70_TO_68_0_CASE__ETC__q19 = 63'd0;
    endcase
  end
endmodule  // mkDoubleFMA

